In [1]:
from scipy.io import loadmat
import pandas as pd
import os
import matplotlib.pyplot as plt
import numpy as np
from mapd import Trial, Table, Sinq
import h5py

from matplotlib.figure import Figure
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
%load_ext autoreload
%autoreload 2
%matplotlib widget

def refresh_table_addons():
    import importlib
    import mapd.table_plotters as tps
    import mapd.table_scalars as tbs
    importlib.reload(tps)
    importlib.reload(tbs)

    for name in dir(tps):
        if name.startswith('_'):
            continue
        attr = getattr(tps, name)
        setattr(Table, name[len("plot_"):], attr)
    
    for name in dir(tbs):
        if name.startswith('_'):
            continue
        if name.startswith('compute_'):
            attr = getattr(tbs, name)
            setattr(Table, name[len("compute_"):], attr)

# Create sinq

In [2]:
sinq = Sinq(sinqname='Figure1')
print(sinq.__repr__())
sinq.df

Found data directory: D:\Data
Sinq(Figure1, 20 rows x 29 params): 0 empties; ['210302_F1_C2', '210331_F2_C1', '210405_F1_C1', '210604_F1_C1', '210903_F3_C1', '210915_F1_C1', '210917_F2_C1', '250226_F2_C1', '250227_F2_C1', '250227_F3_C1', '250228_F1_C1', '250228_F2_C1', '250304_F2_C1', '250304_F3_C1', '250425_F1_C1', '250506_F2_C1', '250514_F1_C1', '250923_F2_C1', '250924_F1_C1', '250924_F2_C1'] x ['parquet', 'Table', 'genotype', 'duration', 'rms_velocity', 'outcome_fractions_no_as_no_mv', 'outcome_fractions_as_off', 'outcome_fractions_rest', 'outcome_fractions_no_as_mv', 'outcome_fractions_probe', 'outcome_fractions_as_off_late', 'outcome_fractions_timeout_fail', 'outcome_fractions_timeout', 'outcome_fractions_info', 'lo_state_median_position', 'hi_state_median_position', 'hi_lo_shift', 'hi_state_on_target', 'lo_state_on_target', 'num_trials', 'blue_fraction', 'blue_toggle_fraction', 'most_common_fiberLED', 'lo_target_off_state', 'hi_target_off_state', 'probe_positive_effort', 'successes', 'hard_successes', 'holding_cost']

,parquet,Table,genotype,duration,rms_velocity,outcome_fractions_no_as_no_mv,outcome_fractions_as_off,outcome_fractions_rest,outcome_fractions_no_as_mv,outcome_fractions_probe,...,num_trials,blue_fraction,blue_toggle_fraction,most_common_fiberLED,lo_target_off_state,hi_target_off_state,probe_positive_effort,successes,hard_successes,holding_cost
210302_F1_C2,LEDFlashWithPiezoCueControl_210302_F1_C2_Table...,None,Hot-Cell-Gal4 (test),6836.72718,32982.968041,0.561250,0.173750,0.118750,0.111250,0.000000,...,800.0,1.000000,0.000000,625_red,0.055824,0.082934,8.684294e+05,78.0,37.0,9.147350e+06
210331_F2_C1,LEDFlashWithPiezoCueControl_210331_F2_C1_Table...,None,Hot-Cell-LexA_Chr;81A06_pJFRC7,8428.02290,142491.573361,0.337240,0.188802,0.117188,0.088542,0.000000,...,768.0,1.000000,0.218289,625_red,0.351254,0.070320,3.672936e+06,39.0,13.0,9.204896e+06
210405_F1_C1,LEDFlashWithPiezoCueControl_210405_F1_C1_Table...,None,Hot-Cell-LexA_Chr;81A06_pJFRC7,6582.81488,34006.653998,0.462382,0.087774,0.112853,0.105016,0.000000,...,638.0,1.000000,0.171378,625_red,0.145846,0.206347,1.349486e+06,34.0,13.0,1.307052e+07
210604_F1_C1,LEDFlashWithPiezoCueControl_210604_F1_C1_Table...,None,Hot-Cell-LexA_Chr;35c09_pJFRC7,3685.79266,44418.935879,0.565714,0.102857,0.120000,0.085714,0.000000,...,350.0,1.000000,0.107143,625_red,0.138731,0.180145,1.728146e+06,15.0,9.0,6.519351e+06
210903_F3_C1,LEDFlashTriggerPiezoControl_210903_F3_C1_Table...,None,Hot-Cell-LexA_Chr;35C09_pJFRC7,6303.51030,45596.022785,0.426667,0.131667,0.120000,0.086667,0.000000,...,600.0,1.000000,0.204545,625_red,0.125386,0.072073,1.898442e+06,37.0,14.0,1.363618e+07
210915_F1_C1,LEDFlashTriggerPiezoControl_210915_F1_C1_Table...,None,Hot-Cell-LexA_Chr;78E05_pJFRC7,5857.48988,45659.433547,0.410463,0.084507,0.120724,0.078471,0.000000,...,497.0,1.000000,0.237986,625_red,0.109020,0.279235,2.327835e+06,27.0,12.0,1.325873e+07
210917_F2_C1,LEDFlashTriggerPiezoControl_210917_F2_C1_Table...,None,Hot-Cell-LexA_Chr;31H05_pJFRC7,5780.00094,74683.629443,0.315498,0.276753,0.121771,0.127306,0.000000,...,542.0,1.000000,0.182773,625_red,0.111971,0.241052,4.262578e+06,50.0,19.0,1.208222e+07
250226_F2_C1,LEDFlashTriggerPiezoControl_250226_F2_C1_Table...,None,SS61350_pJFRC7,9447.21096,506486.281215,0.261153,0.455930,0.110990,0.125136,0.014146,...,919.0,0.751904,1.000000,epi_only,0.238928,0.056086,2.533657e+07,93.0,29.0,2.928704e+07
250227_F2_C1,LEDFlashTriggerPiezoControl_250227_F2_C1_Table...,None,SS61350_pJFRC7,7224.62008,236730.246194,0.478431,0.315033,0.117647,0.054902,0.014379,...,765.0,0.666667,1.000000,epi_only,0.115984,0.042458,7.757883e+06,44.0,29.0,1.284016e+07
250227_F3_C1,LEDFlashTriggerPiezoControl_250227_F3_C1_Table...,None,SS61350_pJFRC7,6078.90756,392467.613033,0.360502,0.333856,0.206897,0.056426,0.012539,...,638.0,1.000000,1.000000,epi_only,0.048098,0.169664,1.715732e+07,27.0,12.0,1.004275e+07
250228_F1_C1,LEDFlashTriggerPiezoControl_250228_F1_C1_Table...,None,SS61350_pJFRC7,7618.77836,265420.814150,0.279156,0.478908,0.107940,0.098015,0.016129,...,806.0,0.627792,1.000000,epi_only,0.194243,0.033546,8.433156e+06,68.0,31.0,1.740252e+07
250228_F2_C1,LEDFlashTriggerPiezoControl_250228_F2_C1_Table...,None,SS61350_pJFRC7,5978.05628,117477.458152,0.626374,0.167975,0.102041,0.043956,0.015699,...,637.0,0.000000,1.000000,epi_only,0.083723,0.101560,5.082797e+06,31.0,23.0,1.093529e+07
250304_F2_C1,LEDFlashTriggerPiezoControl_250304_F2_C1_Table...,None,SS61350_pJFRC7,6903.43650,110196.297362,0.224172,0.136452,0.214425,0.064327,0.023392,...,513.0,0.204678,1.000000,epi_only,0.116809,0.052450,5.109327e+06,28.0,5.0,2.266263e+07
250304_F3_C1,LEDFlashTriggerPiezoControl_250304_F3_C1_Table...,None,SS61350_pJFRC7,13404.06094,190728.766293,0.655862,0.171034,0.100000,0.042759,0.017241,...,1450.0,1.000000,1.000000,epi_only,0.069873,0.041706,1.352463e+07,75.0,45.0,2.341512e+07
250425_F1_C1,LEDFlashTriggerPiezoControl_250425_F1_C1_Table...,None,+;31H05-Gal4_pJFRC7,9197.41092,79575.355853,0.437086,0.155629,0.115894,0.113687,0.016556,...,906.0,1.000000,1.000000,epi_only,0.139695,0.170346,2.704414e+06,88.0,29.0,1.469065e+07
250506_F2_C1,LEDFlashTriggerPiezoControl_250506_F2_C1_Table...,None,+;TH-Gal4_UAS-Kir2_1,4763.53340,30559.291116,0.616633,0.115619,0.162272,0.024341,0.016227,...,493.0,0.000000,1.000000,epi_only,0.078466,0.047868,9.921757e+05,19.0,13.0,1.099932e+07
250514_F1_C1,LEDFlashTriggerPiezoControl_250514_F1_C1_Table...,None,+;TH-Gal4_UAS-Kir2_1,7162.92532,50041.223549,0.390278,0.212500,0.169444,0.093056,0.022222,...,720.0,0.000000,1.000000,epi_only,0.052191,0.192504,2.763766e+06,63.0,22.0,1.418251e+07
250923_F2_C1,LEDFlashTriggerPiezoControl_250923_F2_C1_Table...,None,+;pJFRC7;SS61350,7308.99956,247832.189426,0.367036,0.324100,0.110803,0.065097,0.019391,...,722.0,1.000000,1.000000,epi_only,0.098506,0.105005,9.652646e+06,42.0,20.0,2.164790e+07
250924_F1_C1,LEDFlashTriggerPiezoControl_250924_F1_C1_Table...,None,+;pJFRC7;SS61350,12344.55634,406836.456996,0.153291,0.309288,0.148783,0.109107,0.027953,...,1109.0,1.000000,1.000000,epi_only,0.197542,0.097547,1.649813e+07,97.0,19.0,2.053001e+07
250924_F2_C1,LEDFlashTriggerPiezoControl_250924_F2_C1_Table...,None,+;pJFRC7;SS61350,13902.88682,919198.302288,0.367860,0.221630,0.140899,0.068545,0.026657,...,1313.0,1.000000,1.000000,epi_only,0.073265,0.115133,3.205245e+07,73.0,28.0,3.731554e+07

# Whole cell recordings

### 210302_F1_C2

In [ ]:
# tr = Trial(fn='LEDFlashWithPiezoCueControl_Raw_210302_F1_C2_1.mat')
# tr.params
# tr = Trial(fn='LEDFlashWithPiezoCueControl_Raw_210302_F1_C2_1.mat')
T = Table('LEDFlashWithPiezoCueControl_210302_F1_C2_Table.parquet',progress_bar=True)
# T.assign_column_value('filtercube_status','blue',trial_min =1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','625_red',trial_min =1,write_to_hdf5=True)
T.extract_trial_properties()
# fig,ax = T.plot_outcomes(savefig=True,format='png')
# fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')
sinq.add_table(table=T)
sinq.df

### 210319_F2_C1 - Do not use
What is the deal!? There is an enormous number of points and the distributions is near probe_Zero, but the heatmap shows displacement. Not clear where this is coming from...?

In [ ]:
T = Table('LEDFlashWithPiezoCueControl_210319_F2_C1_Table.parquet',progress_bar=True,add_probestate=False)
# # Found 4 target positions - Counter({('lo', 730.0, -180.0, 60.0): 251, ('hi', 730.0, -260.0, 60.0): 199, ('no_state', 0.0, 520.0, 80.0): 50, ('no_state', 0.0, 450.0, 80.0): 50})
# # T.df.loc[T.df['pyasXPosition']==490,'Trial'].index
# # T.exclude_list_of_trials(T.df.loc[T.df['pyasXPosition']==490,'Trial'].index,reason='unused target position')
# # T.df.loc[T.df['pyasXPosition']==520,'probeZero'] = 730
# # T.df.loc[T.df['pyasXPosition']==450,'probeZero'] = 730
# # T.df.loc[T.df['pyasXPosition']==520,'pyasState'] = 'lo'
# # T.df.loc[T.df['pyasXPosition']==450,'pyasState'] = 'hi'
# # T.df.loc[T.df['pyasXPosition']==450,'pyasState']
# # T.write_column_to_trial_files('pyasState')
# # T.write_column_to_trial_files('probeZero')
# T.assign_column_value('filtercube_status','blue',trial_min =1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','625_red',trial_min =1,write_to_hdf5=True)
T.extract_trial_properties()
fig,ax = T.plot_outcomes(savefig=True,format='png')
fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')
# trial = Trial('LEDFlashWithPiezoCueControl_Raw_210319_F2_C1_1.mat')
# trial.fiberLED

### 210331_F2_C1 - HC-LexA/13XLexAop-ChrimsonR;81A06/pJFRC7 100uL ATR mixed in

In [ ]:
T = Table('LEDFlashWithPiezoCueControl_210331_F2_C1_Table.parquet',progress_bar=True,add_probestate=True)
# T.assign_column_value('filtercube_status','blue',trial_min =1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','625_red',trial_min =1,write_to_hdf5=True)
T.extract_trial_properties()
T.fig_folder = './figpanels'
fig,ax = T.plot_outcomes(savefig=True,format='png')
fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')
# T.df.loc[775,'Trial'].exclude(reason='end_of_data_poorly_conditioned')

### 210405_F1_C1

In [ ]:
T = Table('LEDFlashWithPiezoCueControl_210405_F1_C1_Table.parquet',progress_bar=True,add_probestate=True)
# T.assign_column_value('filtercube_status','blue',trial_min =1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','625_red',trial_min =1,write_to_hdf5=True)
T.extract_trial_properties()
T.fig_folder = './figpanels'
fig,ax = T.plot_outcomes(savefig=True,format='png')
fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')
sinq.add_table(table=T)
sinq.df

### 210602_F1_C1 - Do not use
HC-LexA/13XLexAop-ChrimsonR;35C09/pJFRC7 75 ATR mixed in, no attenuator on LED

In [ ]:
T = Table('LEDFlashWithPiezoCueControl_210602_F1_C1_Table.parquet',progress_bar=True,add_probestate=True)
# Found 7 target positions - Counter({(490.0, 60.0): 241, (390.0, 60.0): 200, (310.0, 60.0): 101, (410.0, 60.0): 51, (380.0, 60.0): 50, (240.0, 60.0): 7, (140.0, 60.0): 1})
# # T.df.loc[T.df['pyasXPosition']==490,'Trial'].index
# # T.exclude_list_of_trials(T.df.loc[T.df['pyasXPosition']==490,'Trial'].index,reason='unused target position')
# # T.df.loc[T.df['pyasXPosition']==520,'probeZero'] = 730
# # T.df.loc[T.df['pyasXPosition']==450,'probeZero'] = 730
# # T.df.loc[T.df['pyasXPosition']==520,'pyasState'] = 'lo'
# # T.df.loc[T.df['pyasXPosition']==450,'pyasState'] = 'hi'
# # T.df.loc[T.df['pyasXPosition']==450,'pyasState']
# # T.write_column_to_trial_files('pyasState')
# # T.write_column_to_trial_files('probeZero')

# T.assign_column_value('filtercube_status','blue',trial_min =1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','625_red',trial_min =1,write_to_hdf5=True)

# trial = Trial('LEDFlashWithPiezoCueControl_Raw_210602_F1_C1_1.mat')
# trial.fiberLED

In [ ]:
T.df.loc[T.df.loc[:,'pyasXPosition']==310].index

In [ ]:
T.fig_folder = './figpanels'
T.extract_trial_properties()
fig,ax,df = T.plot_probe_position_heatmap(index=T.df.index,cmin=-500,cmax=10,format='png')
fig

In [ ]:
T.fig_folder = './figpanels'
print('Table: {}'.format(T))
lo_fig,ax = T.plot_probe_distribution(df_filter={'pyasState':'lo'}, index=T.df.index, bin_min=-500, bin_max=10,format='png',export=False)
hi_fig,ax = T.plot_probe_distribution(df_filter={'pyasState':'hi'}, index=T.df.index, bin_min=-500, bin_max=10,format='png',export=False)
hi_fig

### 210604_F1_C1 - HC-LexA/13XLexAop-ChrimsonR;35C09/pJFRC7 75 ATR mixed in

In [ ]:
T = Table('LEDFlashWithPiezoCueControl_210604_F1_C1_Table.parquet',progress_bar=True,add_probestate=True)
# Found 7 target positions - Counter({(490.0, 60.0): 241, (390.0, 60.0): 200, (310.0, 60.0): 101, (410.0, 60.0): 51, (380.0, 60.0): 50, (240.0, 60.0): 7, (140.0, 60.0): 1})
# # T.df.loc[T.df['pyasXPosition']==490,'Trial'].index
# # T.exclude_list_of_trials(T.df.loc[T.df['pyasXPosition']==490,'Trial'].index,reason='unused target position')
# # T.df.loc[T.df['pyasXPosition']==520,'probeZero'] = 730
# # T.df.loc[T.df['pyasXPosition']==450,'probeZero'] = 730
# # T.df.loc[T.df['pyasXPosition']==520,'pyasState'] = 'lo'
# # T.df.loc[T.df['pyasXPosition']==450,'pyasState'] = 'hi'
# # T.df.loc[T.df['pyasXPosition']==450,'pyasState']
# # T.write_column_to_trial_files('pyasState')
# # T.write_column_to_trial_files('probeZero')

T.assign_column_value('filtercube_status','blue',trial_min =1, write_to_hdf5=True)
T.assign_column_value('fiberLED','625_red',trial_min =1,write_to_hdf5=True)

trial = Trial('LEDFlashWithPiezoCueControl_Raw_210604_F1_C1_1.mat')
trial.fiberLED

In [ ]:
T.fig_folder = './figpanels'
T.extract_trial_properties()
fig,ax,df = T.plot_probe_position_heatmap(index=T.df.index,cmin=-500,cmax=10,format='png')
fig

In [ ]:
T.fig_folder = './figpanels'
print('Table: {}'.format(T))
lo_fig,ax = T.plot_probe_distribution(df_filter={'pyasState':'lo'}, index=T.df.index, bin_min=-500, bin_max=10,format='png',export=False)
hi_fig,ax = T.plot_probe_distribution(df_filter={'pyasState':'hi'}, index=T.df.index, bin_min=-500, bin_max=10,format='png',export=False)
hi_fig

### 210903_F3_C1 - HC-LexA/13XLexAop-ChrimsonR;35C09/pJFRC7 75 ATR mixed in

In [ ]:
T = Table('LEDFlashTriggerPiezoControl_210903_F3_C1_Table.parquet',progress_bar=True,add_probestate=True)

T.assign_column_value('filtercube_status','blue',trial_min =1, write_to_hdf5=True)
T.assign_column_value('fiberLED','625_red',trial_min =1,write_to_hdf5=True)

trial = Trial('LEDFlashWithPiezoCueControl_Raw_210602_F1_C1_1.mat')
trial.fiberLED

In [ ]:
T.fig_folder = './figpanels'
T.extract_trial_properties()
fig,ax,df = T.plot_probe_position_heatmap(index=T.df.index,cmin=-500,cmax=10,format='png')
fig

In [ ]:
T.fig_folder = './figpanels'
print('Table: {}'.format(T))
lo_fig,ax = T.plot_probe_distribution(df_filter={'pyasState':'lo'}, index=T.df.index, bin_min=-500, bin_max=10,format='png',export=False)
hi_fig,ax = T.plot_probe_distribution(df_filter={'pyasState':'hi'}, index=T.df.index, bin_min=-500, bin_max=10,format='png',export=False)
hi_fig

### 210915_F1_C1 - HC-LexA/13XLexAop-ChrimsonR;35C09/pJFRC7 75 ATR mixed in

In [ ]:
# T = Table('LEDFlashTriggerPiezoControl_210915_F1_C1_Table.parquet',progress_bar=True,add_probestate=True)
# Found 5 target positions - Counter({(432.0, 60.0): 208, (332.0, 60.0): 189, (2.0, 0.0): 50, (238.0, 60.0): 50, (338.0, 60.0): 50})

# T.exclude_list_of_trials(index = T.df.loc[T.df['pyasXPosition']==2,'Trial'].index,reason='unused target position')
# T.df.loc[T.df['pyasXPosition']==238,'Trial'].index
# T.df.loc[T.df['pyasXPosition']==238,'probeZero'] = 518
# T.df.loc[T.df['pyasXPosition']==338,'probeZero'] = 518
# T.df.loc[T.df['pyasXPosition']==338,'pyasState'] = 'lo'
# T.df.loc[T.df['pyasXPosition']==238,'pyasState'] = 'hi'
# T.df.loc[T.df['pyasXPosition']==338,'pyasState']

# T.df.loc[T.df['pyasXPosition']==432.0,'probeZero'] = 612
# T.df.loc[T.df['pyasXPosition']==332.0,'probeZero'] = 612
# T.df.loc[T.df['pyasXPosition']==432.0,'pyasState'] = 'lo'
# T.df.loc[T.df['pyasXPosition']==332.0,'pyasState'] = 'hi'
# T.df.loc[T.df['pyasXPosition']==338,'pyasState']
# T.write_column_to_trial_files('pyasState')
# T.write_column_to_trial_files('probeZero')

# T.assign_column_value('filtercube_status','blue',trial_min =1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','625_red',trial_min =1,write_to_hdf5=True)

# trial = Trial('LEDFlashWithPiezoCueControl_Raw_210602_F1_C1_1.mat')
# trial.fiberLED

T = sinq.df.loc['210915_F1_C1','Table']
T

In [ ]:
index = T.df.loc[T.df['probeZero']==612.0].index

In [ ]:
T.fig_folder = './figpanels'
T.extract_trial_properties()
fig,ax,df = T.plot_probe_position_heatmap(index=T.df.loc[T.df['probeZero']==612.0].index,cmin=-500,cmax=10,format='png')
fig

In [ ]:
T.fig_folder = './figpanels'
print('Table: {}'.format(T))
# lo_fig,ax = T.plot_probe_distribution(df_filter={'pyasState':'lo'}, index=T.df.index, bin_min=-500, bin_max=10,format='png',export=False)
# hi_fig,ax = T.plot_probe_distribution(df_filter={'pyasState':'hi'}, index=T.df.index, bin_min=-500, bin_max=10,format='png',export=False)
lo_fig,ax = T.plot_probe_distribution(df_filter={'pyasState':'lo'}, index=index, bin_min=-500, bin_max=10,format='png',export=False)
hi_fig,ax = T.plot_probe_distribution(df_filter={'pyasState':'hi'}, index=index, bin_min=-500, bin_max=10,format='png',export=False)
hi_fig

In [ ]:
lo_fig

### 210917_F2_C1 - HC-LexA/13XLexAop-ChrimsonR;35C09/pJFRC7 75 ATR mixed in

In [ ]:
T = Table('LEDFlashTriggerPiezoControl_210917_F2_C1_Table.parquet',progress_bar=True,add_probestate=True)

T.assign_column_value('filtercube_status','blue',trial_min =1, write_to_hdf5=True)
T.assign_column_value('fiberLED','625_red',trial_min =1,write_to_hdf5=True)

trial = Trial('LEDFlashWithPiezoCueControl_Raw_210602_F1_C1_1.mat')
trial.fiberLED

In [ ]:
T.fig_folder = './figpanels'
T.extract_trial_properties()
fig,ax,df = T.plot_probe_position_heatmap(index=T.df.index,cmin=-500,cmax=10,format='png')
fig

In [ ]:
T.fig_folder = './figpanels'
print('Table: {}'.format(T))
lo_fig,ax = T.plot_probe_distribution(df_filter={'pyasState':'lo'}, index=T.df.index, bin_min=-500, bin_max=10,format='png',export=False)
hi_fig,ax = T.plot_probe_distribution(df_filter={'pyasState':'hi'}, index=T.df.index, bin_min=-500, bin_max=10,format='png',export=False)
hi_fig

In [ ]:
lo_fig

# W+ Blue to Green

SS61350>w+;;pJFRC7 = +;pJFRC7/VT057379-p65ADZp in attP40; R20C08-ZpGdbd in attP2 (SS61350)

### 250226_F2_C1 - SS61350>w+;;pJFRC7

Nice fly_cell. There was the strange anticipation of the target change. There was a very long rest before switching to green LED. But even then

In [ ]:
T = Table('LEDFlashTriggerPiezoControl_250226_F2_C1_Table.parquet')
# T.open_notes_files()
# T.assign_column_value('filtercube_status','blue',trial_min=1,trial_max=691,write_to_hdf5=True)
# print(T.df['filtercube_status'].value_counts())
# T.assign_column_value('filtercube_status','green',trial_min=692,write_to_hdf5=True)
# print(T.df['filtercube_status'].value_counts())
T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)

### 250227_F1_C1 - SS61350>w+;;pJFRC7

Blue then Green. Really nice! Timeouts only begin with the green LED

In [ ]:
T = Table('LEDFlashTriggerPiezoControl_250227_F1_C1_Table.parquet')
# T.open_notes_files()
# T.assign_column_value('filtercube_status','blue',trial_min=1,trial_max=510,write_to_hdf5=True)
# print(T.df['filtercube_status'].value_counts())
# T.assign_column_value('filtercube_status','green',trial_min=511,write_to_hdf5=True)
# print(T.df['filtercube_status'].value_counts())
T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)

### 250227_F2_C1 - SS61350>w+;;pJFRC7

Blue then Green. 
Nice learning! Some more timeouts and more as off trials with Green.

In [ ]:
T = Table('LEDFlashTriggerPiezoControl_250227_F2_C1_Table.parquet')
# T.open_notes_files()
# T.assign_column_value('filtercube_status','blue',trial_min=1,trial_max=510,write_to_hdf5=True)
# print(T.df['filtercube_status'].value_counts())
# T.assign_column_value('filtercube_status','green',trial_min=511,write_to_hdf5=True)
# print(T.df['filtercube_status'].value_counts())
T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
print(T.df['fiberLED'].value_counts())

### 250227_F3_C1 - SS61350>w+;;pJFRC7

?

In [ ]:
T = Table('LEDFlashTriggerPiezoControl_250227_F3_C1_Table.parquet')

# T.add_df_category('blue',trial_min=1,trial_max=638,categories='_filtercube_status_cat')
# T.assign_column_value('filtercube_status','blue',trial_min=1,trial_max=638,write_to_hdf5=True)
T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
print(T.df['fiberLED'].value_counts())
# T.open_notes_files()

In [ ]:
T.open_notes_files()

### 250228_F1_C1 - SS61350>w+;;pJFRC7

Blue then Green. 
This one takes a long time to learn in each block. Some more timeouts and more as off trials with Green.

In [ ]:
T = Table('LEDFlashTriggerPiezoControl_250228_F1_C1_Table.parquet')
T.progress_bar = True
# T.assign_column_value('filtercube_status','blue',trial_min=1,trial_max=507,write_to_hdf5=True)
# print(T.df['filtercube_status'].value_counts())
# T.assign_column_value('filtercube_status','green',trial_min=508,write_to_hdf5=True)
print(T.df['filtercube_status'].value_counts())
T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
print(T.df['fiberLED'].value_counts())

### 250304_F3_C1 - SS61350>w+;;pJFRC7

Blue then Green.

In [ ]:
T = Table('LEDFlashTriggerPiezoControl_250304_F3_C1_Table.parquet')
# T.open_notes_files()
# T.extract_trial_properties()
# val = T.assign_column_value('filtercube_status','blue',trial_min=1,trial_max=1450,write_to_hdf5=True)
T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
print(T.df['fiberLED'].value_counts())

In [ ]:
fig,ax = T.plot_outcomes(savefig=True)
# fname = T.export_some_probe_groups(index=idx, from_zero=True)
# fig = plot_probe_trace_from_pickle(fname)
fig.canvas.draw()
figname =  f"./Figure1/example_outcomes_{T.day}_F{T.fly}_C{T.cell}_{T.genotype}_.svg"
fig.savefig(fname=figname, format='svg')
fig

### 250425_F1_C1 - +;pJFRC7;31H05-Gal4

In [ ]:
T = Table('LEDFlashTriggerPiezoControl_250425_F1_C1_Table.parquet')
# T.assign_column_value('filtercube_status','blue',trial_min=1,write_to_hdf5=True)
# T.open_notes_files()
T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
print(T.df['fiberLED'].value_counts())

### 250923_F1_C1 - +;pJFRC7;31H05-Gal4

In [ ]:
id = '250923_F1_C1'
# sinq.df.drop(index=id)

if id in sinq.df.index:
    T = sinq.restore_table(dayflycell=id,overwrite=True)
    T.extract_trial_properties()
    T.find_successful_trials()
else:
    T = Table(f'LEDFlashTriggerPiezoControl_{id}_Table.parquet')
    T.exclude_trials()
    T.assign_column_value('filtercube_status','blue',trial_min=1, write_to_hdf5=True)
    T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
    T.extract_trial_properties()
    T.find_successful_trials()
    sinq.add_table(table=T)
    sinq.df

fig,ax = T.plot_outcomes(savefig=True,format='png')
fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')

### 250923_F2_C1 - SS61350>w+;;pJFRC7

In [ ]:
id = '250923_F2_C1'
# sinq.df.drop(index=id)

if id in sinq.df.index:
    T = sinq.restore_table(dayflycell=id,overwrite=True)
    T.extract_trial_properties()
    T.find_successful_trials()
else:
    T = Table(f'LEDFlashTriggerPiezoControl_{id}_Table.parquet')
    T.exclude_trials()
    # T.assign_column_value('filtercube_status','blue',trial_min=1, write_to_hdf5=True)
    # T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
    T.extract_trial_properties()
    T.find_successful_trials()
    sinq.add_table(table=T)
    sinq.df

fig,ax = T.plot_outcomes(savefig=True,format='png')
fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')

### 250924_F1_C1 - SS61350>w+;;pJFRC7

In [ ]:
id = '250924_F1_C1'

T = Table(f'LEDFlashTriggerPiezoControl_{id}_Table.parquet')

T.assign_column_value('filtercube_status','blue',trial_min=1, write_to_hdf5=True)
T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
T.extract_trial_properties()
T.find_successful_trials()
fig,ax = T.plot_outcomes(savefig=True,format='png')
fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')
sinq.add_table(table=T)
sinq.df

### 250924_F2_C1 - SS61350>w+;;pJFRC7

Something funny happened here when I tried to exclude certain trials. I ended up excluding some I want to include. I suspect it has more to do with heatmap plotting

In [ ]:
id = '250924_F2_C1'
if id in sinq.df.index:
    T = sinq.restore_table(dayflycell=id)
else:
    T = Table(f'LEDFlashTriggerPiezoControl_{id}_Table.parquet')
    # T.assign_column_value('filtercube_status','blue',trial_min=1, write_to_hdf5=True)
    # T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
    # endofdaytrials = T.df.loc[1093:]
    # T.exclude_list_of_trials(endofdaytrials.index,reason='tired, frustrated poor behavior')
    sinq.add_table(table=T)
    sinq.df

T.extract_trial_properties()
T.find_successful_trials()
fig,ax = T.plot_outcomes(savefig=True,format='png')
fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')

### 250925_F1_C1 - SS61350>w+;;pJFRC7

In [25]:
id = '250925_F1_C1'
if id in sinq.df.index:
    T = sinq.restore_table(dayflycell=id,overwrite=True)
else:
    T = Table(f'LEDFlashTriggerPiezoControl_{id}_Table.parquet')
    # T.assign_column_value('filtercube_status','blue',trial_min=1, write_to_hdf5=True)
    # T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
    # endofdaytrials = T.df.loc[1093:]
    # T.exclude_list_of_trials(endofdaytrials.index,reason='tired, frustrated poor behavior')
    sinq.add_table(table=T)
T.exclude_trials()
T.extract_trial_properties()
T.find_successful_trials()
sinq.add_table(table=T,overwrite=True)
fig,ax = T.plot_outcomes(savefig=True,format='png')
fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')

Found data directory: D:\Data
T = pd.read_parquet("D:\\Data\\250925\\250925_F1_C1\\LEDFlashTriggerPiezoControl_250925_F1_C1_Table.parquet")
Getting trials
Excluding trials:
[Trial(trial=934, 250925_F1_C1, dT=3.21936, ex=True)]
Getting all meta keys
['as_outcome']
Found 2 target positions - Counter({('hi', 630.0, -280.0, 60.0): 475, ('lo', 630.0, -180.0, 60.0): 458})
Writing filtercube_status to each trial
Writing fiberLED to each trial
Excluding trials:
[Trial(trial=934, 250925_F1_C1, dT=3.21936, ex=True)]
no_as_no_mv: 294; no_as_mv: 99; as_off: 378; success: 87; hard_success: 40
duration
rms_velocity
outcome_fractions_no_as_no_mv
outcome_fractions_as_off
outcome_fractions_rest
outcome_fractions_no_as_mv
outcome_fractions_probe
outcome_fractions_as_off_late
outcome_fractions_timeout_fail
outcome_fractions_timeout
outcome_fractions_info
lo_state_median_position
hi_state_median_position
hi_lo_shift
hi_state_on_target
lo_state_on_target
num_trials
blue_fraction
blue_toggle_fraction
most_common_fiberLED
lo_target_off_state
hi_target_off_state
probe_positive_effort
successes
hard_successes
holding_cost
Adding parquet for 250925_F1_C1
Adding Table for 250925_F1_C1
Adding genotype for 250925_F1_C1
Adding duration for 250925_F1_C1
Adding rms_velocity for 250925_F1_C1
Adding outcome_fractions_no_as_no_mv for 250925_F1_C1
Adding outcome_fractions_as_off for 250925_F1_C1
Adding outcome_fractions_rest for 250925_F1_C1
Adding outcome_fractions_no_as_mv for 250925_F1_C1
Adding outcome_fractions_probe for 250925_F1_C1
Adding outcome_fractions_as_off_late for 250925_F1_C1
Adding outcome_fractions_timeout_fail for 250925_F1_C1
Adding outcome_fractions_timeout for 250925_F1_C1
Adding outcome_fractions_info for 250925_F1_C1
Adding lo_state_median_position for 250925_F1_C1
New filter or probe bins, recomputing distributions
Counting downsampled probe positions in bins
Adding hi_state_median_position for 250925_F1_C1
New filter or probe bins, recomputing distributions
Counting downsampled probe positions in bins
Adding hi_lo_shift for 250925_F1_C1
Adding hi_state_on_target for 250925_F1_C1
Using existing probe bins
On target ([-284.] - [-216.]): 0.42 (389607/929145)
Adding lo_state_on_target for 250925_F1_C1
New filter or probe bins, recomputing distributions
Counting downsampled probe positions in bins
On target ([-184.] - [-116.]): 0.62 (547694/880843)
Adding num_trials for 250925_F1_C1
Adding blue_fraction for 250925_F1_C1
filter cube status present
Adding blue_toggle_fraction for 250925_F1_C1
Adding most_common_fiberLED for 250925_F1_C1
Adding lo_target_off_state for 250925_F1_C1
New filter or probe bins, recomputing distributions
Counting downsampled probe positions in bins
On target ([-184.] - [-116.]): 0.18 (169778/929145)
Adding hi_target_off_state for 250925_F1_C1
New filter or probe bins, recomputing distributions
Counting downsampled probe positions in bins
On target ([-284.] - [-216.]): 0.07 (64767/880843)
Adding probe_positive_effort for 250925_F1_C1
Adding successes for 250925_F1_C1
Adding hard_successes for 250925_F1_C1
Adding holding_cost for 250925_F1_C1

posx and posy should be finite values

8
3 of 3 timeouts (100.0%) during blue light
Probe positions dataframe created with 933 trials

In [26]:
sinq.df

,parquet,Table,genotype,duration,rms_velocity,outcome_fractions_no_as_no_mv,outcome_fractions_as_off,outcome_fractions_rest,outcome_fractions_no_as_mv,outcome_fractions_probe,...,num_trials,blue_fraction,blue_toggle_fraction,most_common_fiberLED,lo_target_off_state,hi_target_off_state,probe_positive_effort,successes,hard_successes,holding_cost
210302_F1_C2,LEDFlashWithPiezoCueControl_210302_F1_C2_Table...,None,Hot-Cell-Gal4 (test),6836.72718,32982.968041,0.561250,0.173750,0.118750,0.111250,0.000000,...,800.0,1.000000,0.000000,625_red,0.055824,0.082934,8.684294e+05,78.0,37.0,9.147350e+06
210331_F2_C1,LEDFlashWithPiezoCueControl_210331_F2_C1_Table...,None,Hot-Cell-LexA_Chr;81A06_pJFRC7,8428.02290,142491.573361,0.337240,0.188802,0.117188,0.088542,0.000000,...,768.0,1.000000,0.218289,625_red,0.351254,0.070320,3.672936e+06,39.0,13.0,9.204896e+06
210405_F1_C1,LEDFlashWithPiezoCueControl_210405_F1_C1_Table...,None,Hot-Cell-LexA_Chr;81A06_pJFRC7,6582.81488,34006.653998,0.462382,0.087774,0.112853,0.105016,0.000000,...,638.0,1.000000,0.171378,625_red,0.145846,0.206347,1.349486e+06,34.0,13.0,1.307052e+07
210604_F1_C1,LEDFlashWithPiezoCueControl_210604_F1_C1_Table...,None,Hot-Cell-LexA_Chr;35c09_pJFRC7,3685.79266,44418.935879,0.565714,0.102857,0.120000,0.085714,0.000000,...,350.0,1.000000,0.107143,625_red,0.138731,0.180145,1.728146e+06,15.0,9.0,6.519351e+06
210903_F3_C1,LEDFlashTriggerPiezoControl_210903_F3_C1_Table...,None,Hot-Cell-LexA_Chr;35C09_pJFRC7,6303.51030,45596.022785,0.426667,0.131667,0.120000,0.086667,0.000000,...,600.0,1.000000,0.204545,625_red,0.125386,0.072073,1.898442e+06,37.0,14.0,1.363618e+07
210915_F1_C1,LEDFlashTriggerPiezoControl_210915_F1_C1_Table...,None,Hot-Cell-LexA_Chr;78E05_pJFRC7,5857.48988,45659.433547,0.410463,0.084507,0.120724,0.078471,0.000000,...,497.0,1.000000,0.237986,625_red,0.109020,0.279235,2.327835e+06,27.0,12.0,1.325873e+07
210917_F2_C1,LEDFlashTriggerPiezoControl_210917_F2_C1_Table...,None,Hot-Cell-LexA_Chr;31H05_pJFRC7,5780.00094,74683.629443,0.315498,0.276753,0.121771,0.127306,0.000000,...,542.0,1.000000,0.182773,625_red,0.111971,0.241052,4.262578e+06,50.0,19.0,1.208222e+07
250226_F2_C1,LEDFlashTriggerPiezoControl_250226_F2_C1_Table...,None,SS61350_pJFRC7,9447.21096,506486.281215,0.261153,0.455930,0.110990,0.125136,0.014146,...,919.0,0.751904,1.000000,epi_only,0.238928,0.056086,2.533657e+07,93.0,29.0,2.928704e+07
250227_F2_C1,LEDFlashTriggerPiezoControl_250227_F2_C1_Table...,None,SS61350_pJFRC7,7224.62008,236730.246194,0.478431,0.315033,0.117647,0.054902,0.014379,...,765.0,0.666667,1.000000,epi_only,0.115984,0.042458,7.757883e+06,44.0,29.0,1.284016e+07
250227_F3_C1,LEDFlashTriggerPiezoControl_250227_F3_C1_Table...,None,SS61350_pJFRC7,6078.90756,392467.613033,0.360502,0.333856,0.206897,0.056426,0.012539,...,638.0,1.000000,1.000000,epi_only,0.048098,0.169664,1.715732e+07,27.0,12.0,1.004275e+07
250228_F1_C1,LEDFlashTriggerPiezoControl_250228_F1_C1_Table...,None,SS61350_pJFRC7,7618.77836,265420.814150,0.279156,0.478908,0.107940,0.098015,0.016129,...,806.0,0.627792,1.000000,epi_only,0.194243,0.033546,8.433156e+06,68.0,31.0,1.740252e+07
250228_F2_C1,LEDFlashTriggerPiezoControl_250228_F2_C1_Table...,None,SS61350_pJFRC7,5978.05628,117477.458152,0.626374,0.167975,0.102041,0.043956,0.015699,...,637.0,0.000000,1.000000,epi_only,0.083723,0.101560,5.082797e+06,31.0,23.0,1.093529e+07
250304_F2_C1,LEDFlashTriggerPiezoControl_250304_F2_C1_Table...,None,SS61350_pJFRC7,6903.43650,110196.297362,0.224172,0.136452,0.214425,0.064327,0.023392,...,513.0,0.204678,1.000000,epi_only,0.116809,0.052450,5.109327e+06,28.0,5.0,2.266263e+07
250304_F3_C1,LEDFlashTriggerPiezoControl_250304_F3_C1_Table...,None,SS61350_pJFRC7,13404.06094,190728.766293,0.655862,0.171034,0.100000,0.042759,0.017241,...,1450.0,1.000000,1.000000,epi_only,0.069873,0.041706,1.352463e+07,75.0,45.0,2.341512e+07
250425_F1_C1,LEDFlashTriggerPiezoControl_250425_F1_C1_Table...,None,+;31H05-Gal4_pJFRC7,9197.41092,79575.355853,0.437086,0.155629,0.115894,0.113687,0.016556,...,906.0,1.000000,1.000000,epi_only,0.139695,0.170346,2.704414e+06,88.0,29.0,1.469065e+07
250506_F2_C1,LEDFlashTriggerPiezoControl_250506_F2_C1_Table...,None,+;TH-Gal4_UAS-Kir2_1,4763.53340,30559.291116,0.616633,0.115619,0.162272,0.024341,0.016227,...,493.0,0.000000,1.000000,epi_only,0.078466,0.047868,9.921757e+05,19.0,13.0,1.099932e+07
250514_F1_C1,LEDFlashTriggerPiezoControl_250514_F1_C1_Table...,None,+;TH-Gal4_UAS-Kir2_1,7162.92532,50041.223549,0.390278,0.212500,0.169444,0.093056,0.022222,...,720.0,0.000000,1.000000,epi_only,0.052191,0.192504,2.763766e+06,63.0,22.0,1.418251e+07
250923_F1_C1,LEDFlashTriggerPiezoControl_250923_F1_C1_Table...,"Day 250923, F1, C1: LEDFlashTriggerPiezoContro...",+;pJFRC7;31H05-Gal4,9298.27190,525408.875407,0.132214,0.587618,0.104932,0.087093,0.018888,...,953.0,1.000000,1.000000,epi_only,0.179449,0.097450,2.043835e+07,72.0,15.0,1.537973e+07
250923_F2_C1,LEDFlashTriggerPiezoControl_250923_F2_C1_Table...,"Day 250923, F2, C1: LEDFlashTriggerPiezoContro...",+;pJFRC7;SS61350,7308.99956,247832.189426,0.367036,0.324100,0.110803,0.065097,0.019391,...,722.0,1.000000,1.000000,epi_only,0.098506,0.105005,9.652646e+06,42.0,20.0,2.164790e+07
250924_F1_C1,LEDFlashTriggerPiezoControl_250924_F1_C1_Table...,None,+;pJFRC7;SS61350,12344.55634,406836.456996,0.153291,0.309288,0.148783,0.109107,0.027953,...,1109.0,1.000000,1.000000,epi_only,0.197542,0.097547,1.649813e+07,97.0,19.0,2.053001e+07
250924_F2_C1,LEDFlashTriggerPiezoControl_250924_F2_C1_Table...,None,+;pJFRC7;SS61350,13902.88682,919198.302288,0.367860,0.221630,0.140899,0.068545,0.026657,...,1313.0,1.000000,1.000000,epi_only,0.073265,0.115133,3.205245e+07,73.0,28.0,3.731554e+07
250925_F1_C1,LEDFlashTriggerPiezoControl_250925_F1_C1_Table...,"Day 250925, F1, C1: LEDFlashTriggerPiezoContro...",+;pJFRC7;SS61350,9059.42986,267913.713755,0.315113,0.405145,0.101822,0.106109,0.018221,...,933.0,1.000000,1.000000,epi_only,0.182725,0.073528,8.602142e+06,87.0,40.0,1.368038e+07
250925_F2_C1,LEDFlashTriggerPiezoControl_250925_F2_C1_Table...,"Day 250925, F2, C1: LEDFlashTriggerPiezoContro...",+;pJFRC7;SS61350,15578.91662,486060.149867,0.086861,0.335766,0.170803,0.091971,0.032847,...,1370.0,1.000000,1.000000,epi_only,0.136813,0.137756,1.841428e+07,113.0,24.0,2.048717e+07

### 250925_F2_C1 - SS61350>w+;;pJFRC7

In [21]:
id = '250925_F2_C1'
if id in sinq.df.index:
    T = sinq.restore_table(dayflycell=id,overwrite=True)
    # endofdaytrials = T.df.loc[1081:]
    # T.exclude_list_of_trials(endofdaytrials.index,reason='tired, frustrated poor behavior')
else:
    T = Table(f'LEDFlashTriggerPiezoControl_{id}_Table.parquet')
    T.assign_column_value('filtercube_status','blue',trial_min=1, write_to_hdf5=True)
    T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
    sinq.add_table(table=T)
    sinq.df
T.exclude_trials()
T.extract_trial_properties()
T.find_successful_trials()
fig,ax = T.plot_outcomes(savefig=True,format='png')
fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')

Found data directory: D:\Data
T = pd.read_parquet("D:\\Data\\250925\\250925_F2_C1\\LEDFlashTriggerPiezoControl_250925_F2_C1_Table.parquet")
Getting trials
Excluding trials:
[Trial(trial=1081, 250925_F2_C1, dT=9.28406, ex=True), Trial(trial=1082, 250925_F2_C1, dT=8.74886, ex=True), Trial(trial=1083, 250925_F2_C1, dT=13.9238, ex=True), Trial(trial=1084, 250925_F2_C1, dT=7.97552, ex=True), Trial(trial=1085, 250925_F2_C1, dT=14.52376, ex=True), Trial(trial=1086, 250925_F2_C1, dT=14.02486, ex=True), Trial(trial=1087, 250925_F2_C1, dT=15.05054, ex=True), Trial(trial=1088, 250925_F2_C1, dT=16.84924, ex=True), Trial(trial=1089, 250925_F2_C1, dT=14.69386, ex=True), Trial(trial=1090, 250925_F2_C1, dT=10.0607, ex=True), Trial(trial=1091, 250925_F2_C1, dT=9.24424, ex=True), Trial(trial=1092, 250925_F2_C1, dT=8.69954, ex=True), Trial(trial=1093, 250925_F2_C1, dT=10.49978, ex=True), Trial(trial=1094, 250925_F2_C1, dT=10.45776, ex=True), Trial(trial=1095, 250925_F2_C1, dT=30.81528, ex=True), Trial(trial=1096, 250925_F2_C1, dT=15.87536, ex=True), Trial(trial=1097, 250925_F2_C1, dT=16.1073, ex=True), Trial(trial=1098, 250925_F2_C1, dT=17.22656, ex=True), Trial(trial=1099, 250925_F2_C1, dT=17.83878, ex=True), Trial(trial=1100, 250925_F2_C1, dT=17.4231, ex=True), Trial(trial=1101, 250925_F2_C1, dT=10.07942, ex=True), Trial(trial=1102, 250925_F2_C1, dT=9.22206, ex=True), Trial(trial=1103, 250925_F2_C1, dT=10.7845, ex=True), Trial(trial=1104, 250925_F2_C1, dT=9.36576, ex=True), Trial(trial=1105, 250925_F2_C1, dT=9.699, ex=True), Trial(trial=1106, 250925_F2_C1, dT=31.73346, ex=True), Trial(trial=1107, 250925_F2_C1, dT=15.76608, ex=True), Trial(trial=1108, 250925_F2_C1, dT=16.70268, ex=True), Trial(trial=1109, 250925_F2_C1, dT=17.37962, ex=True), Trial(trial=1110, 250925_F2_C1, dT=14.68934, ex=True), Trial(trial=1111, 250925_F2_C1, dT=14.41908, ex=True), Trial(trial=1112, 250925_F2_C1, dT=10.03548, ex=True), Trial(trial=1113, 250925_F2_C1, dT=9.22122, ex=True), Trial(trial=1114, 250925_F2_C1, dT=10.59956, ex=True), Trial(trial=1115, 250925_F2_C1, dT=7.91504, ex=True), Trial(trial=1116, 250925_F2_C1, dT=9.1834, ex=True), Trial(trial=1117, 250925_F2_C1, dT=32.49908, ex=True), Trial(trial=1118, 250925_F2_C1, dT=15.79968, ex=True), Trial(trial=1119, 250925_F2_C1, dT=16.93414, ex=True), Trial(trial=1120, 250925_F2_C1, dT=14.63964, ex=True), Trial(trial=1121, 250925_F2_C1, dT=17.5248, ex=True), Trial(trial=1122, 250925_F2_C1, dT=16.76582, ex=True), Trial(trial=1123, 250925_F2_C1, dT=10.07396, ex=True), Trial(trial=1124, 250925_F2_C1, dT=9.20888, ex=True), Trial(trial=1125, 250925_F2_C1, dT=10.52282, ex=True), Trial(trial=1126, 250925_F2_C1, dT=8.21134, ex=True), Trial(trial=1127, 250925_F2_C1, dT=8.7881, ex=True), Trial(trial=1128, 250925_F2_C1, dT=31.91128, ex=True), Trial(trial=1129, 250925_F2_C1, dT=15.69726, ex=True), Trial(trial=1130, 250925_F2_C1, dT=16.7078, ex=True), Trial(trial=1131, 250925_F2_C1, dT=16.76568, ex=True), Trial(trial=1132, 250925_F2_C1, dT=15.32544, ex=True), Trial(trial=1133, 250925_F2_C1, dT=15.50804, ex=True), Trial(trial=1134, 250925_F2_C1, dT=10.06588, ex=True), Trial(trial=1135, 250925_F2_C1, dT=9.1984, ex=True), Trial(trial=1136, 250925_F2_C1, dT=7.56098, ex=True), Trial(trial=1137, 250925_F2_C1, dT=9.23812, ex=True), Trial(trial=1138, 250925_F2_C1, dT=9.26128, ex=True), Trial(trial=1139, 250925_F2_C1, dT=28.9655, ex=True), Trial(trial=1140, 250925_F2_C1, dT=15.80652, ex=True), Trial(trial=1141, 250925_F2_C1, dT=16.97644, ex=True), Trial(trial=1142, 250925_F2_C1, dT=17.86516, ex=True), Trial(trial=1143, 250925_F2_C1, dT=14.34956, ex=True), Trial(trial=1144, 250925_F2_C1, dT=14.68058, ex=True), Trial(trial=1145, 250925_F2_C1, dT=10.11508, ex=True), Trial(trial=1146, 250925_F2_C1, dT=9.16856, ex=True), Trial(trial=1147, 250925_F2_C1, dT=10.83368, ex=True), Trial(trial=1148, 250925_F2_C1, dT=8.81462, ex=True), Trial(trial=1149, 250925_F2_C1, dT=8.94296, ex=True), Trial(trial=1150, 250925_F2_C1, dT=32.249, ex=True), Trial(trial=1151, 250925_F2_C1, dT=15.7763, ex=True), Trial(trial=1152, 250925_F2_C1, dT=16.81454, ex=True), Trial(trial=1153, 250925_F2_C1, dT=16.4006, ex=True), Trial(trial=1154, 250925_F2_C1, dT=15.85032, ex=True), Trial(trial=1155, 250925_F2_C1, dT=14.81654, ex=True), Trial(trial=1156, 250925_F2_C1, dT=10.08274, ex=True), Trial(trial=1157, 250925_F2_C1, dT=9.2144, ex=True), Trial(trial=1158, 250925_F2_C1, dT=8.53372, ex=True), Trial(trial=1159, 250925_F2_C1, dT=8.09874, ex=True), Trial(trial=1160, 250925_F2_C1, dT=7.7004, ex=True), Trial(trial=1161, 250925_F2_C1, dT=29.7347, ex=True), Trial(trial=1162, 250925_F2_C1, dT=15.7487, ex=True), Trial(trial=1163, 250925_F2_C1, dT=13.97282, ex=True), Trial(trial=1164, 250925_F2_C1, dT=15.60704, ex=True), Trial(trial=1165, 250925_F2_C1, dT=15.01856, ex=True), Trial(trial=1166, 250925_F2_C1, dT=16.34736, ex=True), Trial(trial=1167, 250925_F2_C1, dT=10.0444, ex=True), Trial(trial=1168, 250925_F2_C1, dT=9.18764, ex=True), Trial(trial=1169, 250925_F2_C1, dT=10.69262, ex=True), Trial(trial=1170, 250925_F2_C1, dT=8.09194, ex=True), Trial(trial=1171, 250925_F2_C1, dT=11.0495, ex=True), Trial(trial=1172, 250925_F2_C1, dT=30.4335, ex=True), Trial(trial=1173, 250925_F2_C1, dT=15.73224, ex=True), Trial(trial=1174, 250925_F2_C1, dT=16.7065, ex=True), Trial(trial=1175, 250925_F2_C1, dT=8.6916, ex=True), Trial(trial=1176, 250925_F2_C1, dT=17.49124, ex=True), Trial(trial=1177, 250925_F2_C1, dT=13.8264, ex=True), Trial(trial=1178, 250925_F2_C1, dT=17.04952, ex=True), Trial(trial=1179, 250925_F2_C1, dT=16.24968, ex=True), Trial(trial=1180, 250925_F2_C1, dT=15.88942, ex=True), Trial(trial=1181, 250925_F2_C1, dT=10.10292, ex=True), Trial(trial=1182, 250925_F2_C1, dT=9.18706, ex=True), Trial(trial=1183, 250925_F2_C1, dT=10.8843, ex=True), Trial(trial=1184, 250925_F2_C1, dT=7.48458, ex=True), Trial(trial=1185, 250925_F2_C1, dT=9.53788, ex=True), Trial(trial=1186, 250925_F2_C1, dT=31.13396, ex=True), Trial(trial=1187, 250925_F2_C1, dT=15.69966, ex=True), Trial(trial=1188, 250925_F2_C1, dT=16.2924, ex=True), Trial(trial=1189, 250925_F2_C1, dT=16.98346, ex=True), Trial(trial=1190, 250925_F2_C1, dT=16.54942, ex=True), Trial(trial=1191, 250925_F2_C1, dT=15.09938, ex=True), Trial(trial=1192, 250925_F2_C1, dT=10.06452, ex=True), Trial(trial=1193, 250925_F2_C1, dT=9.37336, ex=True), Trial(trial=1194, 250925_F2_C1, dT=8.49976, ex=True), Trial(trial=1195, 250925_F2_C1, dT=10.66148, ex=True), Trial(trial=1196, 250925_F2_C1, dT=9.53904, ex=True), Trial(trial=1197, 250925_F2_C1, dT=31.42572, ex=True), Trial(trial=1198, 250925_F2_C1, dT=9.2146, ex=True), Trial(trial=1199, 250925_F2_C1, dT=10.8496, ex=True), Trial(trial=1200, 250925_F2_C1, dT=10.23408, ex=True), Trial(trial=1201, 250925_F2_C1, dT=8.84954, ex=True), Trial(trial=1202, 250925_F2_C1, dT=9.97286, ex=True), Trial(trial=1203, 250925_F2_C1, dT=7.72984, ex=True), Trial(trial=1204, 250925_F2_C1, dT=7.76948, ex=True), Trial(trial=1205, 250925_F2_C1, dT=14.22698, ex=True), Trial(trial=1206, 250925_F2_C1, dT=14.28392, ex=True), Trial(trial=1207, 250925_F2_C1, dT=16.04956, ex=True), Trial(trial=1208, 250925_F2_C1, dT=14.06486, ex=True), Trial(trial=1209, 250925_F2_C1, dT=17.0074, ex=True), Trial(trial=1210, 250925_F2_C1, dT=16.60206, ex=True), Trial(trial=1211, 250925_F2_C1, dT=10.09422, ex=True), Trial(trial=1212, 250925_F2_C1, dT=9.24472, ex=True), Trial(trial=1213, 250925_F2_C1, dT=7.35014, ex=True), Trial(trial=1214, 250925_F2_C1, dT=8.59922, ex=True), Trial(trial=1215, 250925_F2_C1, dT=11.07286, ex=True), Trial(trial=1216, 250925_F2_C1, dT=30.0762, ex=True), Trial(trial=1217, 250925_F2_C1, dT=15.74988, ex=True), Trial(trial=1218, 250925_F2_C1, dT=14.7495, ex=True), Trial(trial=1219, 250925_F2_C1, dT=15.08368, ex=True), Trial(trial=1220, 250925_F2_C1, dT=17.16518, ex=True), Trial(trial=1221, 250925_F2_C1, dT=14.74944, ex=True), Trial(trial=1222, 250925_F2_C1, dT=13.80728, ex=True), Trial(trial=1223, 250925_F2_C1, dT=16.44494, ex=True), Trial(trial=1224, 250925_F2_C1, dT=10.04642, ex=True), Trial(trial=1225, 250925_F2_C1, dT=9.23432, ex=True), Trial(trial=1226, 250925_F2_C1, dT=8.21496, ex=True), Trial(trial=1227, 250925_F2_C1, dT=10.62384, ex=True), Trial(trial=1228, 250925_F2_C1, dT=10.1254, ex=True), Trial(trial=1229, 250925_F2_C1, dT=30.69894, ex=True), Trial(trial=1230, 250925_F2_C1, dT=15.73472, ex=True), Trial(trial=1231, 250925_F2_C1, dT=14.2497, ex=True), Trial(trial=1232, 250925_F2_C1, dT=15.59952, ex=True), Trial(trial=1233, 250925_F2_C1, dT=16.39946, ex=True), Trial(trial=1234, 250925_F2_C1, dT=14.91016, ex=True), Trial(trial=1235, 250925_F2_C1, dT=10.12278, ex=True), Trial(trial=1236, 250925_F2_C1, dT=9.20468, ex=True), Trial(trial=1237, 250925_F2_C1, dT=8.8261, ex=True), Trial(trial=1238, 250925_F2_C1, dT=10.94966, ex=True), Trial(trial=1239, 250925_F2_C1, dT=8.26498, ex=True), Trial(trial=1240, 250925_F2_C1, dT=30.8341, ex=True), Trial(trial=1241, 250925_F2_C1, dT=15.75032, ex=True), Trial(trial=1242, 250925_F2_C1, dT=14.7832, ex=True), Trial(trial=1243, 250925_F2_C1, dT=16.17984, ex=True), Trial(trial=1244, 250925_F2_C1, dT=14.23434, ex=True), Trial(trial=1245, 250925_F2_C1, dT=15.76934, ex=True), Trial(trial=1246, 250925_F2_C1, dT=10.06258, ex=True), Trial(trial=1247, 250925_F2_C1, dT=9.30364, ex=True), Trial(trial=1248, 250925_F2_C1, dT=9.98048, ex=True), Trial(trial=1249, 250925_F2_C1, dT=8.9328, ex=True), Trial(trial=1250, 250925_F2_C1, dT=8.48444, ex=True), Trial(trial=1251, 250925_F2_C1, dT=30.98836, ex=True), Trial(trial=1252, 250925_F2_C1, dT=9.22572, ex=True), Trial(trial=1253, 250925_F2_C1, dT=17.10024, ex=True), Trial(trial=1254, 250925_F2_C1, dT=8.87176, ex=True), Trial(trial=1255, 250925_F2_C1, dT=10.69986, ex=True), Trial(trial=1256, 250925_F2_C1, dT=10.45066, ex=True), Trial(trial=1257, 250925_F2_C1, dT=11.46018, ex=True), Trial(trial=1258, 250925_F2_C1, dT=7.79992, ex=True), Trial(trial=1259, 250925_F2_C1, dT=15.71476, ex=True), Trial(trial=1260, 250925_F2_C1, dT=15.33418, ex=True), Trial(trial=1261, 250925_F2_C1, dT=14.41468, ex=True), Trial(trial=1262, 250925_F2_C1, dT=16.05024, ex=True), Trial(trial=1263, 250925_F2_C1, dT=16.24978, ex=True), Trial(trial=1264, 250925_F2_C1, dT=10.0325, ex=True), Trial(trial=1265, 250925_F2_C1, dT=9.18938, ex=True), Trial(trial=1266, 250925_F2_C1, dT=8.54948, ex=True), Trial(trial=1267, 250925_F2_C1, dT=10.57758, ex=True), Trial(trial=1268, 250925_F2_C1, dT=8.64892, ex=True), Trial(trial=1269, 250925_F2_C1, dT=29.09906, ex=True), Trial(trial=1270, 250925_F2_C1, dT=15.88408, ex=True), Trial(trial=1271, 250925_F2_C1, dT=15.98898, ex=True), Trial(trial=1272, 250925_F2_C1, dT=16.21172, ex=True), Trial(trial=1273, 250925_F2_C1, dT=16.8873, ex=True), Trial(trial=1274, 250925_F2_C1, dT=17.1918, ex=True), Trial(trial=1275, 250925_F2_C1, dT=10.0848, ex=True), Trial(trial=1276, 250925_F2_C1, dT=9.1987, ex=True), Trial(trial=1277, 250925_F2_C1, dT=8.7994, ex=True), Trial(trial=1278, 250925_F2_C1, dT=8.82254, ex=True), Trial(trial=1279, 250925_F2_C1, dT=7.99978, ex=True), Trial(trial=1280, 250925_F2_C1, dT=29.91068, ex=True), Trial(trial=1281, 250925_F2_C1, dT=15.81598, ex=True), Trial(trial=1282, 250925_F2_C1, dT=14.02262, ex=True), Trial(trial=1283, 250925_F2_C1, dT=15.5603, ex=True), Trial(trial=1284, 250925_F2_C1, dT=13.91464, ex=True), Trial(trial=1285, 250925_F2_C1, dT=16.7865, ex=True), Trial(trial=1286, 250925_F2_C1, dT=10.07708, ex=True), Trial(trial=1287, 250925_F2_C1, dT=9.25056, ex=True), Trial(trial=1288, 250925_F2_C1, dT=9.0075, ex=True), Trial(trial=1289, 250925_F2_C1, dT=8.59166, ex=True), Trial(trial=1290, 250925_F2_C1, dT=9.0847, ex=True), Trial(trial=1291, 250925_F2_C1, dT=29.73384, ex=True), Trial(trial=1292, 250925_F2_C1, dT=15.83082, ex=True), Trial(trial=1293, 250925_F2_C1, dT=15.49134, ex=True), Trial(trial=1294, 250925_F2_C1, dT=16.72664, ex=True), Trial(trial=1295, 250925_F2_C1, dT=14.06494, ex=True), Trial(trial=1296, 250925_F2_C1, dT=17.08352, ex=True), Trial(trial=1297, 250925_F2_C1, dT=10.08124, ex=True), Trial(trial=1298, 250925_F2_C1, dT=9.23376, ex=True), Trial(trial=1299, 250925_F2_C1, dT=10.12404, ex=True), Trial(trial=1300, 250925_F2_C1, dT=8.26014, ex=True), Trial(trial=1301, 250925_F2_C1, dT=10.19958, ex=True), Trial(trial=1302, 250925_F2_C1, dT=28.9894, ex=True), Trial(trial=1303, 250925_F2_C1, dT=15.7252, ex=True), Trial(trial=1304, 250925_F2_C1, dT=17.23826, ex=True), Trial(trial=1305, 250925_F2_C1, dT=16.34512, ex=True), Trial(trial=1306, 250925_F2_C1, dT=15.86504, ex=True), Trial(trial=1307, 250925_F2_C1, dT=14.91608, ex=True), Trial(trial=1308, 250925_F2_C1, dT=10.06924, ex=True), Trial(trial=1309, 250925_F2_C1, dT=9.23672, ex=True), Trial(trial=1310, 250925_F2_C1, dT=10.47618, ex=True), Trial(trial=1311, 250925_F2_C1, dT=7.1997, ex=True), Trial(trial=1312, 250925_F2_C1, dT=7.26564, ex=True), Trial(trial=1313, 250925_F2_C1, dT=28.91782, ex=True), Trial(trial=1314, 250925_F2_C1, dT=15.73924, ex=True), Trial(trial=1315, 250925_F2_C1, dT=15.4601, ex=True), Trial(trial=1316, 250925_F2_C1, dT=16.54954, ex=True), Trial(trial=1317, 250925_F2_C1, dT=16.26468, ex=True), Trial(trial=1318, 250925_F2_C1, dT=15.61532, ex=True), Trial(trial=1319, 250925_F2_C1, dT=10.10948, ex=True), Trial(trial=1320, 250925_F2_C1, dT=9.22562, ex=True), Trial(trial=1321, 250925_F2_C1, dT=9.20628, ex=True), Trial(trial=1322, 250925_F2_C1, dT=7.55792, ex=True), Trial(trial=1323, 250925_F2_C1, dT=10.80678, ex=True), Trial(trial=1324, 250925_F2_C1, dT=32.08358, ex=True), Trial(trial=1325, 250925_F2_C1, dT=15.91588, ex=True), Trial(trial=1326, 250925_F2_C1, dT=17.36012, ex=True), Trial(trial=1327, 250925_F2_C1, dT=15.6672, ex=True), Trial(trial=1328, 250925_F2_C1, dT=13.83238, ex=True), Trial(trial=1329, 250925_F2_C1, dT=16.29806, ex=True), Trial(trial=1330, 250925_F2_C1, dT=10.01154, ex=True), Trial(trial=1331, 250925_F2_C1, dT=9.27718, ex=True), Trial(trial=1332, 250925_F2_C1, dT=8.92648, ex=True), Trial(trial=1333, 250925_F2_C1, dT=7.29942, ex=True), Trial(trial=1334, 250925_F2_C1, dT=9.7, ex=True), Trial(trial=1335, 250925_F2_C1, dT=32.4246, ex=True), Trial(trial=1336, 250925_F2_C1, dT=15.77408, ex=True), Trial(trial=1337, 250925_F2_C1, dT=16.3888, ex=True), Trial(trial=1338, 250925_F2_C1, dT=15.49498, ex=True), Trial(trial=1339, 250925_F2_C1, dT=14.30334, ex=True), Trial(trial=1340, 250925_F2_C1, dT=16.73922, ex=True), Trial(trial=1341, 250925_F2_C1, dT=10.03192, ex=True), Trial(trial=1342, 250925_F2_C1, dT=9.24074, ex=True), Trial(trial=1343, 250925_F2_C1, dT=10.34794, ex=True), Trial(trial=1344, 250925_F2_C1, dT=7.46592, ex=True), Trial(trial=1345, 250925_F2_C1, dT=9.81856, ex=True), Trial(trial=1346, 250925_F2_C1, dT=32.58222, ex=True), Trial(trial=1347, 250925_F2_C1, dT=15.6995, ex=True), Trial(trial=1348, 250925_F2_C1, dT=14.09984, ex=True), Trial(trial=1349, 250925_F2_C1, dT=17.1006, ex=True), Trial(trial=1350, 250925_F2_C1, dT=13.89834, ex=True), Trial(trial=1351, 250925_F2_C1, dT=17.46126, ex=True), Trial(trial=1352, 250925_F2_C1, dT=10.08216, ex=True), Trial(trial=1353, 250925_F2_C1, dT=9.24464, ex=True), Trial(trial=1354, 250925_F2_C1, dT=10.27582, ex=True), Trial(trial=1355, 250925_F2_C1, dT=11.07278, ex=True), Trial(trial=1356, 250925_F2_C1, dT=8.61118, ex=True), Trial(trial=1357, 250925_F2_C1, dT=31.24906, ex=True), Trial(trial=1358, 250925_F2_C1, dT=15.8147, ex=True), Trial(trial=1359, 250925_F2_C1, dT=14.60046, ex=True), Trial(trial=1360, 250925_F2_C1, dT=15.38362, ex=True), Trial(trial=1361, 250925_F2_C1, dT=16.49944, ex=True), Trial(trial=1362, 250925_F2_C1, dT=14.5592, ex=True), Trial(trial=1363, 250925_F2_C1, dT=10.03196, ex=True), Trial(trial=1364, 250925_F2_C1, dT=9.20784, ex=True), Trial(trial=1365, 250925_F2_C1, dT=10.96494, ex=True), Trial(trial=1366, 250925_F2_C1, dT=8.24998, ex=True), Trial(trial=1367, 250925_F2_C1, dT=10.2724, ex=True), Trial(trial=1368, 250925_F2_C1, dT=31.3817, ex=True), Trial(trial=1369, 250925_F2_C1, dT=15.75182, ex=True), Trial(trial=1370, 250925_F2_C1, dT=17.64134, ex=True), Trial(trial=1371, 250925_F2_C1, dT=15.984, ex=True)]
Getting all meta keys
['as_outcome', 'fiberLED', 'filtercube_status']
Found 2 target positions - Counter({('hi', 630.0, -280.0, 60.0): 575, ('lo', 630.0, -180.0, 60.0): 505})
Excluding trials:

posx and posy should be finite values

no_as_no_mv: 118; no_as_mv: 124; as_off: 449; success: 110; hard_success: 24
8
61 of 61 timeouts (100.0%) during blue light
Probe positions dataframe created with 1080 trials

## w+ Green to Blue

### 250228_F2_C1 - SS61350>w+;;pJFRC7

Green then Blue

In [ ]:
T = Table('LEDFlashTriggerPiezoControl_250228_F2_C1_Table.parquet')
# T.add_df_category('green',trial_min=51,trial_max=713,categories='_filtercube_status_cat')
# T = sinq.df.loc['250228_F2_C1','Table']
# T.assign_column_value('filtercube_status','green',trial_min=51,trial_max=713,write_to_hdf5=True)
print(T.df['filtercube_status'].value_counts())
T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
print(T.df['fiberLED'].value_counts())

### 250304_F2_C1 - SS61350>w+;;pJFRC7

In [ ]:
T = Table('LEDFlashTriggerPiezoControl_250304_F2_C1_Table.parquet')
# T = sinq.df.loc['250304_F2_C1','Table']
# T.assign_column_value('filtercube_status','green',trial_min=1,trial_max=408,write_to_hdf5=True)
# print(T.df['filtercube_status'].value_counts())
# T.assign_column_value('filtercube_status','blue',trial_min=409,trial_max=513,write_to_hdf5=True)
# print(T.df['filtercube_status'].value_counts())
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# print(T.df['fiberLED'].value_counts())

### 250506_F2_C1 >- +;TH-Gal4;UAS-Kir2.1

In [ ]:
sinq

In [ ]:
T = Table('LEDFlashTriggerPiezoControl_250506_F2_C1_Table.parquet')
# T.open_notes_files()

# T.assign_column_value('filtercube_status','green',trial_min=1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
T.extract_trial_properties()
fig,ax = T.plot_outcomes(savefig=True,format='png')
fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')

# solution_ran_out = T.df.loc[494:]
# solution_ran_out.index
# T.exclude_list_of_trials(solution_ran_out.index,'solution_ran_out')
sinq.add_table(table=T)
sinq.df

In [ ]:
fig = Figure(figsize = (8,6),dpi=200)
ax = fig.add_subplot(1,1,1)
T.plot_some_probe_groups(T.df.loc[410:430,:].index,ax=ax,force_pos=True)
fig

### 250514_F1_C1 >- +;TH-Gal4;UAS-Kir2.1

In [ ]:
# T = Table('LEDFlashTriggerPiezoControl_250514_F1_C1_Table.parquet')
# # T.open_notes_files()

# # T.assign_column_value('filtercube_status','green',trial_min=1, write_to_hdf5=True)
# # T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# T.extract_trial_properties()
fig,ax = T.plot_outcomes(savefig=True,format='png')
fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')

# solution_ran_out = T.df.loc[494:]
# solution_ran_out.index
# T.exclude_list_of_trials(solution_ran_out.index,'solution_ran_out')
sinq.add_table(table=T)
sinq.df

In [ ]:
fig = Figure(figsize = (8,6),dpi=200)
ax = fig.add_subplot(1,1,1)
T.plot_some_probe_groups(T.df.loc[410:430,:].index,ax=ax,force_pos=True)
fig

# Sinqing and plotting

In [ ]:
for id in sinq.df.index:
    T = sinq.restore_table(id)
    T.fig_folder = './figpanels'
    T.extract_trial_properties()
    fig,ax = T.plot_outcomes(savefig=True,format='png')
    # fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')

In [ ]:
sinq.sync