# Import

In [1]:
from scipy.io import loadmat
import pandas as pd
import os
import matplotlib.pyplot as plt
import numpy as np
from mapd import Trial, Table, Sinq
import h5py

%load_ext autoreload
%autoreload 2


%matplotlib widget

def refresh_table_addons():
    import importlib
    import mapd.table_plotters as tps
    import mapd.table_scalars as tbs
    importlib.reload(tps)
    importlib.reload(tbs)

    for name in dir(tps):
        if name.startswith('_'):
            continue
        attr = getattr(tps, name)
        setattr(Table, name[len("plot_"):], attr)
    
    for name in dir(tbs):
        if name.startswith('_'):
            continue
        if name.startswith('compute_'):
            attr = getattr(tbs, name)
            setattr(Table, name[len("compute_"):], attr)




# Standard plotting
def run_plots(T):
    fig,ax = T.plot_outcomes(savefig=True,format='png')
    fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')

    df_filters = {'all':None,
              'hi':{'pyasState':'hi'},
              'lo':{'pyasState':'lo'},}

    for filt_key in df_filters.keys():
        dff = df_filters[filt_key]
        fig,ax = T.plot_probe_distribution(binwidth=2,bin_min=-500,bin_max=10,
                                df_filter=dff,index=None,savefig=False,format='png',
                                export=True)

# Load Sinq

In [25]:
# sinq = Sinq(sinqname='Figure3')
# print(sinq.__repr__())

# sinq.df
# sinq_g = subset_sinq(source=sinq_g,rows=g_idx,name='Figure6_mutant_pca')

sinq = Sinq(sinqname='dataset_3_genetic_manipulations')
print(sinq.__repr__())
# sinq.display_df()

Found data directory: D:\Data
Sinq(dataset_3_genetic_manipulations, 36 rows x 33 params): 102 empties; ['241205_F2_C1', '241205_F3_C1', '241219_F1_C1', '241219_F2_C1', '241220_F1_C1', '241220_F2_C1', '250127_F1_C1', '250127_F2_C1', '250128_F1_C1', '250204_F1_C1', '250204_F2_C1', '250211_F2_C1', '250211_F3_C1', '250317_F1_C1', '250317_F2_C1', '250318_F1_C1', '250318_F2_C1', '250318_F3_C1', '250320_F1_C1', '250320_F2_C1', '250325_F1_C1', '250423_F1_C1', '250423_F2_C1', '250506_F1_C1', '250507_F1_C1', '250507_F2_C1', '250509_F2_C1', '250514_F1_C1', '250515_F1_C1', '251114_F1_C2', '251217_F2_C1', '260527_F1_C1', '260527_F4_C1', '260605_F1_C1', '260605_F2_C1', '260605_F3_C1'] x ['Table', 'parquet', 'genotype', 'notes', 'duration', 'rms_velocity', 'outcome_fractions_no_as_no_mv', 'outcome_fractions_as_off', 'outcome_fractions_rest', 'outcome_fractions_no_as_mv', 'outcome_fractions_probe', 'outcome_fractions_as_off_late', 'outcome_fractions_timeout_fail', 'outcome_fractions_timeout', 'outcome_fractions_info', 'lo_state_median_position', 'hi_state_median_position', 'hi_lo_shift', 'hi_state_on_target', 'lo_state_on_target', 'num_trials', 'blue_fraction', 'blue_toggle_fraction', 'most_common_fiberLED', 'lo_target_off_state', 'hi_target_off_state', 'probe_positive_effort', 'successes', 'hard_successes', 'holding_cost', 'rest_time_fraction', 'drift_time_fraction', 'move_time_fraction']

In [24]:
# sinq.restore_table(sinq.df.index[0])
# sinq.add_column('rest_time_fraction')
# sinq.add_column('drift_time_fraction')
# sinq.add_column('move_time_fraction')

sinq.restore_table('250320_F2_C1')
sinq.sync_row('250320_F1_C1', overwrite=False)

Found data directory: D:\Data
T = pd.read_parquet("D:\\Data\\250320\\250320_F2_C1\\LEDFlashTriggerPiezoControl_250320_F2_C1_Table.parquet")
Getting trials
Excluding trials:
[Trial(trial=238, 250320_F2_C1, dT=16.49746, ex=True)]
Getting all meta keys
['as_outcome', 'fiberLED', 'filtercube_status']
Found 2 target positions - Counter({('hi', 640.0, 360.0, -280.0, 60.0): 506, ('lo', 640.0, 460.0, -180.0, 60.0): 489})
Table and all computations for Index(['Table', 'parquet', 'genotype', 'notes', 'duration', 'rms_velocity',
       'outcome_fractions_no_as_no_mv', 'outcome_fractions_as_off',
       'outcome_fractions_rest', 'outcome_fractions_no_as_mv',
       'outcome_fractions_probe', 'outcome_fractions_as_off_late',
       'outcome_fractions_timeout_fail', 'outcome_fractions_timeout',
       'outcome_fractions_info', 'lo_state_median_position',
       'hi_state_median_position', 'hi_lo_shift', 'hi_state_on_target',
       'lo_state_on_target', 'num_trials', 'blue_fraction',
       'blue_toggle_fraction', 'most_common_fiberLED', 'lo_target_off_state',
       'hi_target_off_state', 'probe_positive_effort', 'successes',
       'hard_successes', 'holding_cost', 'rest_time_fraction',
       'drift_time_fraction', 'move_time_fraction'],
      dtype='object') already exists.
Overwrite = False. Skipping addition.

Table                             Day 250320, F1, C1: LEDFlashTriggerPiezoContro...
parquet                           LEDFlashTriggerPiezoControl_250320_F1_C1_Table...
genotype                                                       +;iav-GAL4_UAS-Kir21
notes                             {'text': 'IAV Kir2.1 in [+] background', 'tags...
duration                                                                 7482.59076
rms_velocity                                                          249119.133081
outcome_fractions_no_as_no_mv                                              0.349229
outcome_fractions_as_off                                                   0.274895
outcome_fractions_rest                                                     0.106592
outcome_fractions_no_as_mv                                                 0.119215
outcome_fractions_probe                                                     0.01683
outcome_fractions_as_off_late                                              0.051893
outcome_fractions_timeout_fail                                              0.01122
outcome_fractions_timeout                                                  0.070126
outcome_fractions_info                                                          0.0
lo_state_median_position                                                     -152.0
hi_state_median_position                                                     -194.0
hi_lo_shift                                                                   -42.0
hi_state_on_target                                                         0.249186
lo_state_on_target                                                         0.732919
num_trials                                                                    713.0
blue_fraction                                                                   0.0
blue_toggle_fraction                                                            1.0
most_common_fiberLED                                                       epi_only
lo_target_off_state                                                        0.341911
hi_target_off_state                                                         0.08796
probe_positive_effort                                                9947831.661956
successes                                                                      73.0
hard_successes                                                                 20.0
holding_cost                                                        12446843.968383
rest_time_fraction                                                          0.30759
drift_time_fraction                                                        0.326053
move_time_fraction                                                         0.366357
Name: 250320_F1_C1, dtype: object

In [20]:
sinq.df.loc[sinq.has_tag('+') & sinq.has_tag('iav')]

,Table,parquet,genotype,notes,duration,rms_velocity,outcome_fractions_no_as_no_mv,outcome_fractions_as_off,outcome_fractions_rest,outcome_fractions_no_as_mv,...,most_common_fiberLED,lo_target_off_state,hi_target_off_state,probe_positive_effort,successes,hard_successes,holding_cost,rest_time_fraction,drift_time_fraction,move_time_fraction
250317_F1_C1,None,LEDFlashTriggerPiezoControl_250317_F1_C1_Table...,iav-Gal4_+;+;UAS-Kir2_1,"{'text': 'IAV Kir2.1 in [+] background', 'tags...",10180.17464,329807.278486,0.196685,0.415470,0.100552,0.093923,...,epi_only,0.451019,0.011547,1.146889e+07,76.0,27.0,1.677123e+07,NaN,NaN,NaN
250317_F2_C1,None,LEDFlashTriggerPiezoControl_250317_F2_C1_Table...,iav-Gal4_+;+;UAS-Kir2_1,"{'text': 'IAV Kir2.1 in [+] background', 'tags...",4481.36362,114307.615892,0.299539,0.241935,0.195853,0.041475,...,epi_only,0.054323,0.078473,4.141990e+06,15.0,8.0,1.856917e+07,NaN,NaN,NaN
250318_F1_C1,None,LEDFlashTriggerPiezoControl_250318_F1_C1_Table...,iav-Gal4_+;+;UAS-Kir2_1,"{'text': 'IAV Kir2.1 in [+] background', 'tags...",4131.61472,55085.014357,0.000000,0.698765,0.113580,0.000000,...,epi_only,0.104848,0.059979,2.507546e+06,4.0,4.0,1.097565e+07,NaN,NaN,NaN
250318_F2_C1,None,LEDFlashTriggerPiezoControl_250318_F2_C1_Table...,iav-Gal4_+;+;UAS-Kir2_1,"{'text': 'IAV Kir2.1 in [+] background', 'tags...",3093.76034,103569.392089,0.258555,0.212928,0.174905,0.064639,...,epi_only,0.193671,0.104843,5.004862e+06,11.0,3.0,1.067722e+07,NaN,NaN,NaN
250318_F3_C1,None,LEDFlashTriggerPiezoControl_250318_F3_C1_Table...,iav-Gal4_+;+;UAS-Kir2_1,"{'text': 'IAV Kir2.1 in [+] background', 'tags...",7735.69050,180545.584549,0.238849,0.202878,0.162590,0.082014,...,epi_only,0.071288,0.084014,7.588673e+06,40.0,16.0,2.147418e+07,NaN,NaN,NaN
250320_F1_C1,None,LEDFlashTriggerPiezoControl_250320_F1_C1_Table...,iav-Gal4_+;+;UAS-Kir2_1,"{'text': 'IAV Kir2.1 in [+] background', 'tags...",7482.59076,249119.133081,0.349229,0.274895,0.106592,0.119215,...,epi_only,0.341911,0.087960,9.947832e+06,73.0,20.0,1.244684e+07,NaN,NaN,NaN
250320_F2_C1,None,LEDFlashTriggerPiezoControl_250320_F2_C1_Table...,iav-Gal4_+;+;UAS-Kir2_1,"{'text': 'IAV Kir2.1 in [+] background', 'tags...",10781.66048,133520.440517,0.143574,0.323293,0.165663,0.100402,...,epi_only,0.127576,0.026278,4.401777e+06,75.0,23.0,1.557481e+07,NaN,NaN,NaN
250325_F1_C1,None,LEDFlashTriggerPiezoControl_250325_F1_C1_Table...,iav-Gal4_+;+;UAS-Kir2_1,"{'text': 'IAV Kir2.1 in [+] background', 'tags...",6372.63770,62549.881701,0.212963,0.118519,0.231481,0.053704,...,epi_only,0.174573,0.194133,1.965641e+06,14.0,8.0,1.249335e+07,NaN,NaN,NaN
250423_F1_C1,None,LEDFlashTriggerPiezoControl_250423_F1_C1_Table...,+;iav-Gal4_UAS-Kir2_1,"{'text': 'IAV Kir2.1 in [+] background', 'tags...",2441.71894,12552.563459,0.216495,0.113402,0.221649,0.082474,...,epi_only,0.136435,0.045187,1.205903e+06,10.0,4.0,1.154684e+07,NaN,NaN,NaN
250423_F2_C1,None,LEDFlashTriggerPiezoControl_250423_F2_C1_Table...,+;iav-Gal4_UAS-Kir2_1,"{'text': 'IAV Kir2.1 in [+] background', 'tags...",6640.11538,217555.298298,0.078370,0.501567,0.103448,0.122257,...,epi_only,0.206810,0.087918,7.784995e+06,69.0,8.0,1.582882e+07,NaN,NaN,NaN
251217_F2_C1,None,LEDFlashTriggerPiezoControl_251217_F2_C1_Table...,iav_UAS-TeTx,"{'text': 'IAV TeTx in [+] background', 'tags':...",5823.91622,804064.273054,0.011532,0.866557,0.000000,0.121911,...,epi_only,0.068425,0.030010,2.801166e+07,23.0,1.0,1.012131e+07,NaN,NaN,NaN

# Behavior with drivers (WT or w)

## Green to Blue LED behavior

### 250127_F1_C1 - w[1118];pJFRC7;31H05-Gal4

In [ ]:
id = '250127_F1_C1'

# T = Table('LEDFlashTriggerPiezoControl_250127_F1_C1_Table.parquet')
# T.assign_column_value('filtercube_status','green',trial_min=4,trial_max=416, write_to_hdf5=True)
# T.assign_column_value('filtercube_status','blue',trial_min=417, write_to_hdf5=True) 
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# T.plot_outcomes(savefig=True)
# fig,ax = T.plot_outcomes(savefig=True,format='png')

# df_filter = {'pyasState':'hi','_filtercube_status_cat':'green'}
# early_index = T.df.index[0:100]
# late_index = T.df.index[100:]

# T.plot_probe_distribution(filter=None,index=None,bin_min=-500,bin_max=10,savefig=True)
# plt.close()

# plt.close()

sinq.set_note(
    dayflycell = id,
    text= 'w',
    tags=['w','green','blue'],
)
# sinq.add_table(table=T)
# sinq.df

### 250127_F2_C1 - w[1118];pJFRC7;31H05-Gal4

In [ ]:

id = '250127_F2_C1'
# T = Table('LEDFlashTriggerPiezoControl_250127_F2_C1_Table.parquet')
# T.assign_column_value('filtercube_status','green',trial_min=4,trial_max=415, write_to_hdf5=True)
# T.assign_column_value('filtercube_status','blue',trial_min=417, write_to_hdf5=True) 
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# fig,ax = T.plot_outcomes(savefig=True,format='png')
# fig

sinq.set_note(
    dayflycell = id,
    text= 'w',
    tags=['w','green','blue'],
)

# sinq.add_table(table=T)
# sinq.df

### 250128_F1_C1 - w[1118];pJFRC7;31H05-Gal4

In [ ]:
id = '250128_F1_C1'

# T = Table('LEDFlashTriggerPiezoControl_250128_F1_C1_Table.parquet')
# T.assign_column_value('filtercube_status','green',trial_min=2,trial_max=582, write_to_hdf5=True)
# T.assign_column_value('filtercube_status','blue',trial_min=583, write_to_hdf5=True) 
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# fig,ax = T.plot_outcomes(savefig=True,format='png')

sinq.set_note(
    dayflycell = id,
    text= 'w',
    tags=['w','green','blue'],
)

# T.exclude_list_of_trials(poor_tracking.index,'poor_tracking')
# solution_ran_out = T.df.loc[350:374]
# solution_ran_out.index
# T.exclude_list_of_trials(solution_ran_out.index,'solution_ran_out')
# sinq.add_table(table=T)
# sinq.df

### 250204_F1_C1 - w[1118];pJFRC7;31H05-Gal4

In [ ]:
id = '250204_F1_C1'

# T = Table('LEDFlashTriggerPiezoControl_250204_F1_C1_Table.parquet')
# T.add_df_category('green',trial_min=1,trial_max=576,categories='_filtercube_status_cat')
# T.add_df_category('blue',trial_min=577,categories='_filtercube_status_cat')
# T.assign_column_value('filtercube_status','green',trial_min=1,trial_max=576, write_to_hdf5=True)
# T.assign_column_value('filtercube_status','blue',trial_min=577, write_to_hdf5=True) 
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# fig,ax = T.plot_outcomes(savefig=True,format='png')
# fig
# fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')
# sinq.add_table(table=T)
# sinq.df

sinq.set_note(
    dayflycell = id,
    text= 'w',
    tags=['w','green','blue'],
)

### 250204_F2_C1 - w[1118];pJFRC7;31H05-Gal4

In [ ]:
id = '250204_F2_C1'

# T = Table('LEDFlashTriggerPiezoControl_250204_F2_C1_Table.parquet')
# T.add_df_category('green',trial_min=1,trial_max=408,categories='_filtercube_status_cat')
# T.add_df_category('blue',trial_min=409,categories='_filtercube_status_cat')
# T.assign_column_value('filtercube_status','green',trial_min=1,trial_max=408, write_to_hdf5=True)
# T.assign_column_value('filtercube_status','blue',trial_min=409, write_to_hdf5=True) 
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# fig,ax = T.plot_outcomes(savefig=True,format='png')
# fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')
# sinq.add_table(table=T)
# sinq.df

sinq.set_note(
    dayflycell = id,
    text= 'w',
    tags=['w','green','blue'],
)

## Blue to Green

### 250211_F2_C1 - w[1118];pJFRC7;31H05-Gal4

In [ ]:
id = '250211_F2_C1'

# T = Table('LEDFlashTriggerPiezoControl_250211_F2_C1_Table.parquet')
# T.add_df_category('blue',trial_min=1,trial_max=354,categories='_filtercube_status_cat')
# T.add_df_category('green',trial_min=355,categories='_filtercube_status_cat')
# T.assign_column_value('filtercube_status','blue',trial_min=1,trial_max=354, write_to_hdf5=True)
# T.assign_column_value('filtercube_status','green',trial_min=355, write_to_hdf5=True) 
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# fig,ax = T.plot_outcomes(savefig=True,format='png')
# fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')
# sinq.add_table(table=T)
# sinq.df

sinq.set_note(
    dayflycell = id,
    text= 'w',
    tags=['w','blue','green',],
)

### 250211_F3_C1 - w[1118];pJFRC7;31H05-Gal4

In [ ]:
id = '250211_F3_C1'

# T = Table('LEDFlashTriggerPiezoControl_250211_F3_C1_Table.parquet')
# # T.add_df_category('blue',trial_min=1,trial_max=489,categories='_filtercube_status_cat')
# # T.add_df_category('green',trial_min=490,categories='_filtercube_status_cat')
# T.assign_column_value('filtercube_status','blue',trial_min=1,trial_max=489, write_to_hdf5=True)
# T.assign_column_value('filtercube_status','green',trial_min=490, write_to_hdf5=True) 
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# fig,ax = T.plot_outcomes(savefig=True,format='png')
# fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')
# sinq.add_table(table=T)
# sinq.df

sinq.set_note(
    dayflycell = id,
    text= 'w',
    tags=['w','blue','green',],
)

# IAV Kir2.1 in [w] background

These are with w;;UAS-Kir2.1

## 241205_F2_C1 - w;+;iav-gal4/uas-kir2.1

In [ ]:
id = '241205_F2_C1'

# T = Table('LEDFlashTriggerPiezoControl_241205_F2_C1_Table.parquet')
# T.assign_column_value('filtercube_status','blue',trial_min=1, write_to_hdf5=True)
# # T.assign_column_value('filtercube_status','green',trial_min=490, write_to_hdf5=True) 
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# fig,ax = T.plot_outcomes(savefig=True,format='png')
# fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')
# sinq.add_table(table=T)
# sinq.df

# sinq,T = run_compute(sinq,id)
# run_plots(T)

sinq.set_note(
    dayflycell = id,
    text= 'IAV Kir2.1 in [w] background',
    tags=['w','iav','blue','green',],
)

## 241205_F3_C1 - w;+;iav-gal4/uas-kir2.1

In [ ]:
id = '241205_F3_C1'

# T = Table('LEDFlashTriggerPiezoControl_241205_F3_C1_Table.parquet')
# T.assign_column_value('filtercube_status','blue',trial_min=1, write_to_hdf5=True)
# # T.assign_column_value('filtercube_status','green',trial_min=490, write_to_hdf5=True) 
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# fig,ax = T.plot_outcomes(savefig=True,format='png')
# fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')
# sinq.add_table(table=T)
# sinq.df

# sinq,T = run_compute(sinq,id)
# run_plots(T)

# T.compute_trial_method(method_name='probe_positive_effort')
# T.plot_trial_computations(method_name='probe_positive_effort')

sinq.set_note(
    dayflycell = id,
    text= 'IAV Kir2.1 in [w] background',
    tags=['w','iav','blue','green',],
)

## 241219_F1_C1 - w;+;iav-gal4/uas-kir2.1

Blue then Green.

In [ ]:
id = '241219_F1_C1'

# T = Table('LEDFlashTriggerPiezoControl_241219_F1_C1_Table.parquet')

# T.assign_column_value('filtercube_status','blue',trial_min=1,trial_max=624, write_to_hdf5=True)
# T.assign_column_value('filtercube_status','green',trial_min=625,trial_max=800, write_to_hdf5=True) 
# T.assign_column_value('filtercube_status','blue',trial_min=801, write_to_hdf5=True)
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# fig,ax = T.plot_outcomes(savefig=True,format='png')
# fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')
# sinq.add_table(table=T)
# sinq.df

# sinq,T = run_compute(sinq,id)
# run_plots(T)

sinq.set_note(
    dayflycell = id,
    text= 'IAV Kir2.1 in [w] background',
    tags=['w','iav','blue','green',],
)

## 241219_F2_C1 - w;+;iav-gal4/uas-kir2.1

Blue then Green.

In [ ]:
id = '241219_F2_C1'

# T = Table('LEDFlashTriggerPiezoControl_241219_F2_C1_Table.parquet')
# T.assign_column_value('filtercube_status','blue',trial_min=1,trial_max=520, write_to_hdf5=True)
# T.assign_column_value('filtercube_status','green',trial_min=521, write_to_hdf5=True) 
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# fig,ax = T.plot_outcomes(savefig=True,format='png')
# fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')
# sinq.add_table(table=T)
# sinq.df

# sinq,T = run_compute(sinq,id)
# run_plots(T)

sinq.set_note(
    dayflycell = id,
    text= 'IAV Kir2.1 in [w] background',
    tags=['w','iav','blue','green',],
)

## 241220_F1_C1 - w;+;iav-gal4/uas-kir2.1

Green then Blue then Green.

In [ ]:
id = '241220_F1_C1'

# T = Table('LEDFlashTriggerPiezoControl_241220_F1_C1_Table.parquet')
# T.assign_column_value('filtercube_status','green',trial_min=1,trial_max=104, write_to_hdf5=True)
# T.assign_column_value('filtercube_status','blue',trial_min=105,trial_max=566, write_to_hdf5=True) 
# T.assign_column_value('filtercube_status','green',trial_min=567, write_to_hdf5=True)
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# fig,ax = T.plot_outcomes(savefig=True,format='png')
# fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')
# sinq.add_table(table=T)
# sinq.df
# id = '241220_F1_C1'
# sinq,T = run_compute(sinq,id)
# run_plots(T)

sinq.set_note(
    dayflycell = id,
    text= 'IAV Kir2.1 in [w] background',
    tags=['w','iav','green','blue',],
)

## 241220_F2_C1 - w;+;iav-gal4/uas-kir2.1

Blue then Green.

In [ ]:
id = '241220_F2_C1'

# # T = Table('LEDFlashTriggerPiezoControl_241220_F2_C1_Table.parquet')

# T.assign_column_value('filtercube_status','green',trial_min=1,trial_max=104, write_to_hdf5=True)
# T.assign_column_value('filtercube_status','green',trial_min=105,trial_max=572, write_to_hdf5=True) 
# T.assign_column_value('filtercube_status','blue',trial_min=573, write_to_hdf5=True)
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# fig,ax = T.plot_outcomes(savefig=True,format='png')
# fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')
# sinq.add_table(table=T)
# sinq.df

# sinq,T = run_compute(sinq,id)
# run_plots(T)


sinq.set_note(
    dayflycell = id,
    text= 'IAV Kir2.1 in [w] background',
    tags=['w','iav','green','blue',],
)

# IAV Kir2.1 in [+] background

## Blue

### 250317_F1_C1 - +;+;iav-gal4/uas-kir2.1

Blue

In [ ]:

# T = Table('LEDFlashTriggerPiezoControl_250317_F1_C1_Table.parquet')
# # T.open_notes_files()
# # T.exclude_list_of_trials(T.df.loc[83:86].index,reason='probe slipped, can kick')
# T.assign_column_value('filtercube_status','blue',trial_min=1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# fig,ax = T.plot_outcomes(savefig=True,format='png')
# fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')
# sinq.add_table(table=T)
# sinq.df
id = '250317_F1_C1'
# sinq,T = run_compute(sinq,id)
# run_plots(T)

sinq.clear_note(id)
sinq.set_note(
    dayflycell = id,
    text= 'IAV Kir2.1 in [+] background',
    tags=['+','iav','blue',],
)

### 250317_F2_C1 - +;+;iav-gal4/uas-kir2.1

Blue.

In [ ]:
# T = Table('LEDFlashTriggerPiezoControl_250317_F2_C1_Table.parquet')
# # T.open_notes_files()
# # T.assign_column_value('filtercube_status','blue',trial_min=1, write_to_hdf5=True)
# # T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# # fig,ax = T.plot_outcomes(savefig=True,format='png')
# # fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')
# # sinq.add_table(table=T)
# # sinq.df
id = '250317_F2_C1'
# sinq,T = run_compute(sinq,id)
# run_plots(T)

sinq.set_note(
    dayflycell = id,
    text= 'IAV Kir2.1 in [+] background',
    tags=['+','iav','blue',],
)

### 250318_F1_C1 - +;+;iav-gal4/uas-kir2.1

Blue

In [ ]:
# T = Table('LEDFlashTriggerPiezoControl_250318_F1_C1_Table.parquet')
# # T.open_notes_files()
# T.assign_column_value('filtercube_status','blue',trial_min=1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# T.extract_trial_properties()
# fig,ax = T.plot_outcomes(savefig=True,format='png')
# fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')
# sinq.add_table(table=T)
# sinq.df
id = '250318_F1_C1'

# sinq,T = run_compute(sinq,id)
# run_plots(T)

sinq.set_note(
    dayflycell = id,
    text= 'IAV Kir2.1 in [+] background',
    tags=['+','iav','blue',],
)

### 250318_F2_C1 - +;+;iav-gal4/uas-kir2.1

Blue

In [ ]:
id = '250318_F2_C1'

# T = Table('LEDFlashTriggerPiezoControl_250318_F2_C1_Table.parquet')
# # T.open_notes_files()
# T.assign_column_value('filtercube_status','blue',trial_min=1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# T.extract_trial_properties()
# fig,ax = T.plot_outcomes(savefig=True,format='png')
# fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')
# sinq.add_table(table=T)
# sinq.df
# sinq,T = run_compute(sinq,id)
# run_plots(T)

sinq.set_note(
    dayflycell = id,
    text= 'IAV Kir2.1 in [+] background',
    tags=['+','iav','blue',],
)

### 250318_F3_C1 - +;+;iav-gal4/uas-kir2.1

Blue

In [ ]:
# T = Table('LEDFlashTriggerPiezoControl_250318_F3_C1_Table.parquet')
# # T.open_notes_files()
# T.assign_column_value('filtercube_status','blue',trial_min=1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# T.extract_trial_properties()
# fig,ax = T.plot_outcomes(savefig=True,format='png')
# fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')
# sinq.add_table(table=T)
# sinq.df
id = '250318_F3_C1'

sinq.set_note(
    dayflycell = id,
    text= 'IAV Kir2.1 in [+] background',
    tags=['+','iav','blue',],
)

### 250423_F1_C1 - +;+;iav-gal4/uas-kir2.1

Blue

In [ ]:
id = '250423_F1_C1'

# T = Table('LEDFlashTriggerPiezoControl_250423_F1_C1_Table.parquet')
# T.assign_column_value('filtercube_status','blue',trial_min=1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# T.extract_trial_properties()
# fig,ax = T.plot_outcomes(savefig=True,format='png')
# fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')
# sinq.add_table(table=T)
# sinq.df
# sinq,T = run_compute(sinq,id)
# run_plots(T)

sinq.set_note(
    dayflycell = id,
    text= 'IAV Kir2.1 in [+] background',
    tags=['+','iav','blue',],
)

## Green (4)

In [ ]:
# Standard compute
def run_green_trials_compute(sinq,id):
    if id in sinq.df.index:
        T = sinq.restore_table(dayflycell=id,overwrite=True)
        # endofdaytrials = T.df.loc[1081:]
        # T.exclude_list_of_trials(endofdaytrials.index,reason='tired, frustrated poor behavior')
    else:
        T = Table(f'LEDFlashTriggerPiezoControl_{id}_Table.parquet')
        T.assign_column_value('filtercube_status','green',trial_min=1, write_to_hdf5=True)
        T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
        T.as_outcome_recompute()
        sinq.add_table(table=T)
        sinq.df
    T.exclude_trials()
    T.extract_trial_properties()
    T.find_successful_trials()
    return sinq,T

### 250320_F1_C1 - +;+;iav-gal4/uas-kir2.1

Green

In [ ]:
# T = Table('LEDFlashTriggerPiezoControl_250320_F1_C1_Table.parquet')
# # T.open_notes_files()
# T.assign_column_value('filtercube_status','green',trial_min=1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# T.extract_trial_properties()
# fig,ax = T.plot_outcomes(savefig=True,format='png')
# fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')
# sinq.add_table(table=T)
# sinq.df
id = '250320_F1_C1'
# sinq,T = run_green_trials_compute(sinq,id)
# run_plots(T)

sinq.set_note(
    dayflycell = id,
    text= 'IAV Kir2.1 in [+] background',
    tags=['+','iav','green',],
)

### 250320_F2_C1 - +;+;iav-gal4/uas-kir2.1

Green

In [ ]:
id = '250320_F2_C1'

# T = Table('LEDFlashTriggerPiezoControl_250320_F2_C1_Table.parquet')

# T.assign_column_value('filtercube_status','green',trial_min=1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# T.extract_trial_properties()
# fig,ax = T.plot_outcomes(savefig=True,format='png')
# fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')
# sinq.add_table(table=T)
# sinq.df

# sinq,T = run_green_trials_compute(sinq,id)
# run_plots(T)

sinq.set_note(
    dayflycell = id,
    text= 'IAV Kir2.1 in [+] background',
    tags=['+','iav','green',],
)

In [ ]:
sinq.display_df()['tags']

### 250325_F1_C1 - +;+;iav-gal4/uas-kir2.1

In [ ]:
id = '250325_F1_C1'

# T = Table('LEDFlashTriggerPiezoControl_250325_F1_C1_Table.parquet')
# # T.open_notes_files()
# T.assign_column_value('filtercube_status','green',trial_min=1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# T.extract_trial_properties()
# fig,ax = T.plot_outcomes(savefig=True,format='png')
# fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')
# sinq.add_table(table=T)
# sinq.df

# sinq,T = run_green_trials_compute(sinq,id)
# run_plots(T)

sinq.set_note(
    dayflycell = id,
    text= 'IAV Kir2.1 in [+] background',
    tags=['+','iav','green',],
)

### 250423_F2_C1 - +;+;iav-gal4/uas-kir2.1

Green

In [ ]:
id = '250423_F2_C1'

# T = Table('LEDFlashTriggerPiezoControl_250423_F2_C1_Table.parquet')
# # T.open_notes_files()

# T.assign_column_value('filtercube_status','green',trial_min=1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# T.extract_trial_properties()
# fig,ax = T.plot_outcomes(savefig=True,format='png')
# fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')
# sinq.add_table(table=T)
# sinq.df
# id = '250423_F2_C1'
# sinq,T = run_green_trials_compute(sinq,id)
# run_plots(T)

sinq.set_note(
    dayflycell = id,
    text= 'IAV Kir2.1 in [+] background',
    tags=['+','iav','green',],
)

# IAV > UAS-TeTx

## 251217_F2_C1

In [ ]:
id = '251217_F2_C1'
# T = Table(f'LEDFlashTriggerPiezoControl_{id}_Table.parquet')
# T.assign_column_value('filtercube_status','blue',trial_min=1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)

# T.exclude_trials()
# T.extract_trial_properties()
# T.find_successful_trials()

# run_plots(T)

# sinq.add_table(table=T)
# sinq.drop_tables()

sinq.set_note(
    dayflycell = id,
    text= 'IAV TeTx in [+] background',
    tags=['+','iav','blue','TeTx'],
)

## 251218_F4_C1

In [ ]:
# id = '251218_F4_C1'
# Not adding it. 251217_F2_C1 is better, but I don't think this construct worked here. Deriving the WT white background 
# again, and using Kir2.1 in the mean time. 

# T = Table(f'LEDFlashTriggerPiezoControl_{id}_Table.parquet')
# T.assign_column_value('filtercube_status','blue',trial_min=1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)

# T.exclude_trials()
# T.extract_trial_properties()
# T.find_successful_trials()

# run_plots(T)

# sinq.add_table(table=T)
# sinq.drop_tables()

# sinq.set_note(
#     dayflycell = id,
#     text= 'IAV TeTx in [+] background',
#     tags=['+','iav','green',],
# )

# TH-Gal4>GFP (using WT white allele)

# TH-Gal4>Kir2.1

## Blue

### 250506_F1_C1

In [ ]:
id = '250506_F1_C1'

# T = Table(f'LEDFlashTriggerPiezoControl_{id}_Table.parquet')

# T.assign_column_value('filtercube_status','blue',trial_min=1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# T.extract_trial_properties()

# sinq.add_table(table=T)

# run_plots(T)

sinq.set_note(
    dayflycell = id,
    text= 'TH>Kir2.1',
    tags=['DANs','TH','PPL','blue'],
)

Found data directory: D:\Data
T = pd.read_parquet("D:\\Data\\250506\\250506_F1_C1\\LEDFlashTriggerPiezoControl_250506_F1_C1_Table.parquet")
Getting trials
Excluding trials:
[]
Getting all meta keys
['as_outcome', 'fiberLED', 'filtercube_status']
Found 4 target positions - Counter({('hi', 630.0, 350.0, -280.0, 60.0): 196, ('hi', 580.0, 300.0, -280.0, 60.0): 171, ('lo', 580.0, 400.0, -180.0, 60.0): 153, ('lo', 630.0, 450.0, -180.0, 60.0): 151})
Adding Table for 250506_F1_C1
Adding parquet for 250506_F1_C1
Adding genotype for 250506_F1_C1
Adding duration for 250506_F1_C1
Adding rms_velocity for 250506_F1_C1
Adding outcome_fractions_no_as_no_mv for 250506_F1_C1
Adding outcome_fractions_as_off for 250506_F1_C1
Adding outcome_fractions_rest for 250506_F1_C1
Adding outcome_fractions_no_as_mv for 250506_F1_C1
Adding outcome_fractions_probe for 250506_F1_C1
Adding outcome_fractions_as_off_late for 250506_F1_C1
Adding outcome_fractions_timeout_fail for 250506_F1_C1
Adding outcome_fractions_timeout for 250506_F1_C1
Adding outcome_fractions_info for 250506_F1_C1
Adding lo_state_median_position for 250506_F1_C1
pyasState
New filter or probe bins, recomputing distributions
Counting downsampled probe positions in bins
Adding hi_state_median_position for 250506_F1_C1
pyasState
New filter or probe bins, recomputing distributions
Counting downsampled probe positions in bins
Adding hi_lo_shift for 250506_F1_C1
Adding hi_state_on_target for 250506_F1_C1
pyasState
Using existing probe bins
On target ([-284.] - [-216.]): 0.22 (170651/758812)
Adding lo_state_on_target for 250506_F1_C1
pyasState
New filter or probe bins, recomputing distributions
Counting downsampled probe positions in bins
On target ([-184.] - [-116.]): 0.44 (287763/653887)
Adding num_trials for 250506_F1_C1
Adding blue_fraction for 250506_F1_C1
filter cube status present
Adding blue_toggle_fraction for 250506_F1_C1
Adding most_common_fiberLED for 250506_F1_C1
Adding lo_target_off_state for 250506_F1_C1
pyasState
New filter or probe bins, recomputing distributions
Counting downsampled probe positions in bins
On target ([-184.] - [-116.]): 0.09 (71255/758812)
Adding hi_target_off_state for 250506_F1_C1
pyasState
New filter or probe bins, recomputing distributions
Counting downsampled probe positions in bins
On target ([-284.] - [-216.]): 0.05 (30472/653887)
Adding probe_positive_effort for 250506_F1_C1
Adding successes for 250506_F1_C1

posx and posy should be finite values

no_as_no_mv: 146; no_as_mv: 49; as_off: 246; success: 34; hard_success: 17
Adding hard_successes for 250506_F1_C1
Adding holding_cost for 250506_F1_C1
8
2 of 2 timeouts (100.0%) during blue light
Probe positions dataframe created with 671 trials
New filter or probe bins, recomputing distributions
Counting downsampled probe positions in bins

./figpanels\exports/250506_F1_C1_+;UAS-Kir21;TH-GAL4_probe_dist_nofilt_1_671.pkl
pyasState
New filter or probe bins, recomputing distributions
Counting downsampled probe positions in bins
On target ([-284.] - [-216.]): 0.22 (170651/758812)
hi (1-671)
Saving figure: ./figpanels/250506_F1_C1_+;UAS-Kir21;TH-GAL4_probe_dist_hi_1_671.png
./figpanels\exports/250506_F1_C1_+;UAS-Kir21;TH-GAL4_probe_dist_hi_1_671.pkl
pyasState
New filter or probe bins, recomputing distributions
Counting downsampled probe positions in bins
On target ([-184.] - [-116.]): 0.44 (287763/653887)
lo (1-671)
Saving figure: ./figpanels/250506_F1_C1_+;UAS-Kir21;TH-GAL4_probe_dist_lo_1_671.png
./figpanels\exports/250506_F1_C1_+;UAS-Kir21;TH-GAL4_probe_dist_lo_1_671.pkl

## Green

### 250506_F2_C1

In [ ]:
# id = '250506_F2_C1'

# I guess I'm not adding this one here. it's part of dataset1 because it learns so well. Ignore it.

# T = Table(f'LEDFlashTriggerPiezoControl_{id}_Table.parquet')
# T.open_notes_files()

# T.assign_column_value('filtercube_status','green',trial_min=1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# T.extract_trial_properties()
# fig,ax = T.plot_outcomes(savefig=True,format='png')
# fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')
# sinq.add_table(table=T)
# sinq.df

# sinq.set_note(
#     dayflycell = id,
#     text= 'TH>Kir2.1',
#     tags=['DANs','TH','PPL','green'],
# )

### 250507_F1_C1

In [24]:
id = '250507_F1_C1'

# T = Table(f'LEDFlashTriggerPiezoControl_{id}_Table.parquet')
# T.open_notes_files()

# T.assign_column_value('filtercube_status','green',trial_min=1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# T.extract_trial_properties()
# fig,ax = T.plot_outcomes(savefig=True,format='png')
# fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')
# sinq.add_table(table=T)
# sinq.df

sinq.set_note(
    dayflycell = id,
    text= 'TH>Kir2.1',
    tags=['DANs','TH','PPL','green'],
)

### 250507_F2_C1

In [23]:
id = '250507_F2_C1'

# T = Table(f'LEDFlashTriggerPiezoControl_{id}_Table.parquet')
# T.open_notes_files()

# T.assign_column_value('filtercube_status','green',trial_min=1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# T.extract_trial_properties()
# fig,ax = T.plot_outcomes(savefig=True,format='png')
# fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')
# sinq.add_table(table=T)
# sinq.df

sinq.set_note(
    dayflycell = id,
    text= 'TH>Kir2.1',
    tags=['DANs','TH','PPL','green'],
)

### 250509_F1_C1

In [5]:
id = '250509_F1_C1'

# T = Table(f'LEDFlashTriggerPiezoControl_{id}_Table.parquet')

# T.assign_column_value('filtercube_status','green',trial_min=1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# T.extract_trial_properties()
# fig,ax = T.plot_outcomes(savefig=True,format='png')
# fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')
# sinq.add_table(table=T)
# sinq.df

# T = sinq.restore_table(id)

# poor_tracking = T.df.loc[310:]
# poor_tracking.index
# T.exclude_list_of_trials(poor_tracking.index,'poor_tracking')
# T.extract_trial_properties()

# sinq.set_note(
#     dayflycell = id,
#     text= 'TH>Kir2.1',
#     tags=['DANs','TH','PPL','green'],
# )

# Don't use this one, pulling too much, maybe interesting, but do this with new flies

# run_plots(T)

sinq.delete_table(id)

Deleted 250509_F1_C1 from Sinq.

In [6]:
sinq.df.index

Index(['241205_F2_C1', '241205_F3_C1', '241219_F1_C1', '241219_F2_C1',
       '241220_F1_C1', '241220_F2_C1', '250127_F1_C1', '250127_F2_C1',
       '250128_F1_C1', '250204_F1_C1', '250204_F2_C1', '250211_F2_C1',
       '250211_F3_C1', '250317_F1_C1', '250317_F2_C1', '250318_F1_C1',
       '250318_F2_C1', '250318_F3_C1', '250320_F1_C1', '250320_F2_C1',
       '250325_F1_C1', '250423_F1_C1', '250423_F2_C1', '250506_F1_C1',
       '250507_F1_C1', '250507_F2_C1', '250509_F2_C1', '250514_F1_C1',
       '250515_F1_C1', '251114_F1_C2', '251217_F2_C1', '260527_F1_C1',
       '260527_F4_C1', '260605_F1_C1', '260605_F2_C1', '260605_F3_C1'],
      dtype='object')

### 250509_F2_C1

In [21]:
id = '250509_F2_C1'

# T = Table(f'LEDFlashTriggerPiezoControl_{id}_Table.parquet')
# # T.open_notes_files()

# T.assign_column_value('filtercube_status','green',trial_min=1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# T.extract_trial_properties()
# fig,ax = T.plot_outcomes(savefig=True,format='png')
# fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')
# sinq.add_table(table=T)
# sinq.df

sinq.set_note(
    dayflycell = id,
    text= 'TH>Kir2.1',
    tags=['DANs','TH','PPL','green'],
)

### 250514_F1_C1 Training.  Part of the control dataset for some reason?

In [ ]:
id = '250514_F1_C1'

# Note, tried training the fly initially.

# T = Table(f'LEDFlashTriggerPiezoControl_{id}_Table.parquet')

# T.assign_column_value('filtercube_status','green',trial_min=1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# T.extract_trial_properties()
# sinq.add_table(table=T)
# run_plots(T)

sinq.set_note(
    dayflycell = id,
    text= 'TH>Kir2.1',
    tags=['DANs','TH','PPL','green'],
)

In [26]:
sinq.df

,Table,parquet,genotype,notes,duration,rms_velocity,outcome_fractions_no_as_no_mv,outcome_fractions_as_off,outcome_fractions_rest,outcome_fractions_no_as_mv,...,num_trials,blue_fraction,blue_toggle_fraction,most_common_fiberLED,lo_target_off_state,hi_target_off_state,probe_positive_effort,successes,hard_successes,holding_cost
241205_F2_C1,None,LEDFlashTriggerPiezoControl_241205_F2_C1_Table...,iav_Kir2_1,"{'text': 'IAV Kir2.1 in [w] background', 'tags...",4592.04334,1.037038e+05,0.083984,0.630859,0.152344,0.103516,...,512.0,1.000000,1.0,epi_only,0.371842,0.024624,3.129737e+06,64.0,8.0,5.745730e+06
241205_F3_C1,None,LEDFlashTriggerPiezoControl_241205_F3_C1_Table...,iav_Kir2_1,"{'text': 'IAV Kir2.1 in [w] background', 'tags...",4601.99376,1.995216e+05,0.003891,0.762646,0.155642,0.042802,...,514.0,1.000000,1.0,epi_only,0.264464,0.049193,6.841562e+06,20.0,0.0,7.592188e+06
241219_F1_C1,None,LEDFlashTriggerPiezoControl_241219_F1_C1_Table...,iav_Kir2_1,"{'text': 'IAV Kir2.1 in [w] background', 'tags...",8427.33492,2.468955e+05,0.000000,0.759193,0.151839,0.000000,...,843.0,0.053381,1.0,epi_only,0.145026,0.023368,6.295168e+06,0.0,0.0,8.077882e+06
241219_F2_C1,None,LEDFlashTriggerPiezoControl_241219_F2_C1_Table...,iav_Kir2_1,"{'text': 'IAV Kir2.1 in [w] background', 'tags...",5633.13292,1.485294e+05,0.000000,0.703642,0.172185,0.024834,...,604.0,0.000000,1.0,epi_only,0.212010,0.043292,4.128245e+06,14.0,0.0,6.042135e+06
241220_F1_C1,None,LEDFlashTriggerPiezoControl_241220_F1_C1_Table...,iav_Kir2_1,"{'text': 'IAV Kir2.1 in [w] background', 'tags...",6633.59082,2.480747e+05,0.000000,0.798077,0.153846,0.015110,...,728.0,0.000000,1.0,epi_only,0.221039,0.027496,6.949634e+06,11.0,0.0,8.077262e+06
241220_F2_C1,None,LEDFlashTriggerPiezoControl_241220_F2_C1_Table...,iav_Kir2_1,"{'text': 'IAV Kir2.1 in [w] background', 'tags...",7837.07546,2.913358e+05,0.007212,0.713942,0.153846,0.037260,...,832.0,0.312500,1.0,epi_only,0.213848,0.023861,8.781938e+06,28.0,0.0,1.333849e+07
250127_F1_C1,None,LEDFlashTriggerPiezoControl_250127_F1_C1_Table...,31H05_pJFRC7,"{'text': 'w', 'tags': ['blue', 'green', 'w'], ...",6800.32020,3.596394e+05,0.027510,0.707015,0.154058,0.049519,...,727.0,0.433287,1.0,epi_only,0.171928,0.039667,8.867315e+06,42.0,3.0,7.057058e+06
250127_F2_C1,None,LEDFlashTriggerPiezoControl_250127_F2_C1_Table...,31H05_pJFRC7,"{'text': 'w', 'tags': ['blue', 'green', 'w'], ...",5484.01952,3.742404e+05,0.033670,0.680135,0.146465,0.069024,...,594.0,0.304714,1.0,epi_only,0.090299,0.055188,1.212134e+07,34.0,2.0,7.109523e+06
250128_F1_C1,None,LEDFlashTriggerPiezoControl_250128_F1_C1_Table...,31H05_pJFRC7,"{'text': 'w', 'tags': ['blue', 'green', 'w'], ...",6574.20504,5.108770e+05,0.098901,0.649725,0.153846,0.083791,...,728.0,0.285714,1.0,epi_only,0.122484,0.046467,2.343239e+07,54.0,8.0,2.088457e+07
250204_F1_C1,None,LEDFlashTriggerPiezoControl_250204_F1_C1_Table...,31H05_pJFRC7,"{'text': 'w', 'tags': ['blue', 'green', 'w'], ...",7588.12330,3.860837e+05,0.112965,0.541720,0.138639,0.134788,...,779.0,0.261874,1.0,epi_only,0.205880,0.090884,1.855656e+07,100.0,15.0,1.836187e+07
250204_F2_C1,None,LEDFlashTriggerPiezoControl_250204_F2_C1_Table...,31H05_pJFRC7,"{'text': 'w', 'tags': ['blue', 'green', 'w'], ...",6167.51242,2.720300e+05,0.074875,0.610649,0.109817,0.094842,...,601.0,0.322795,1.0,epi_only,0.100465,0.047083,8.607858e+06,35.0,5.0,1.186020e+07
250211_F2_C1,None,LEDFlashTriggerPiezoControl_250211_F2_C1_Table...,31H05_pJFRC7,"{'text': 'w', 'tags': ['blue', 'green', 'w'], ...",5751.68406,1.975381e+05,0.081673,0.426295,0.103586,0.045817,...,502.0,0.000000,1.0,epi_only,0.105772,0.067062,8.466208e+06,27.0,9.0,1.093400e+07
250211_F3_C1,None,LEDFlashTriggerPiezoControl_250211_F3_C1_Table...,31H05_pJFRC7,"{'text': 'w', 'tags': ['blue', 'green', 'w'], ...",7776.88952,1.826313e+05,0.061931,0.357013,0.131148,0.038251,...,549.0,0.000000,1.0,epi_only,0.074012,0.007877,5.137689e+06,11.0,4.0,2.923919e+06
250317_F1_C1,None,LEDFlashTriggerPiezoControl_250317_F1_C1_Table...,iav-Gal4_+;+;UAS-Kir2_1,"{'text': 'IAV Kir2.1 in [+] background', 'tags...",10180.17464,3.298073e+05,0.196685,0.415470,0.100552,0.093923,...,905.0,1.000000,1.0,epi_only,0.451019,0.011547,1.146889e+07,76.0,27.0,1.677123e+07
250317_F2_C1,None,LEDFlashTriggerPiezoControl_250317_F2_C1_Table...,iav-Gal4_+;+;UAS-Kir2_1,"{'text': 'IAV Kir2.1 in [+] background', 'tags...",4481.36362,1.143076e+05,0.299539,0.241935,0.195853,0.041475,...,434.0,1.000000,1.0,epi_only,0.054323,0.078473,4.141990e+06,15.0,8.0,1.856917e+07
250318_F1_C1,None,LEDFlashTriggerPiezoControl_250318_F1_C1_Table...,iav-Gal4_+;+;UAS-Kir2_1,"{'text': 'IAV Kir2.1 in [+] background', 'tags...",4131.61472,5.508501e+04,0.000000,0.698765,0.113580,0.000000,...,405.0,1.000000,1.0,epi_only,0.104848,0.059979,2.507546e+06,4.0,4.0,1.097565e+07
250318_F2_C1,None,LEDFlashTriggerPiezoControl_250318_F2_C1_Table...,iav-Gal4_+;+;UAS-Kir2_1,"{'text': 'IAV Kir2.1 in [+] background', 'tags...",3093.76034,1.035694e+05,0.258555,0.212928,0.174905,0.064639,...,263.0,1.000000,1.0,epi_only,0.193671,0.104843,5.004862e+06,11.0,3.0,1.067722e+07
250318_F3_C1,None,LEDFlashTriggerPiezoControl_250318_F3_C1_Table...,iav-Gal4_+;+;UAS-Kir2_1,"{'text': 'IAV Kir2.1 in [+] background', 'tags...",7735.69050,1.805456e+05,0.238849,0.202878,0.162590,0.082014,...,695.0,1.000000,1.0,epi_only,0.071288,0.084014,7.588673e+06,40.0,16.0,2.147418e+07
250320_F1_C1,None,LEDFlashTriggerPiezoControl_250320_F1_C1_Table...,iav-Gal4_+;+;UAS-Kir2_1,"{'text': 'IAV Kir2.1 in [+] background', 'tags...",7482.59076,2.491191e+05,0.349229,0.274895,0.106592,0.119215,...,713.0,0.000000,1.0,epi_only,0.341911,0.087960,9.947832e+06,73.0,20.0,1.244684e+07
250320_F2_C1,None,LEDFlashTriggerPiezoControl_250320_F2_C1_Table...,iav-Gal4_+;+;UAS-Kir2_1,"{'text': 'IAV Kir2.1 in [+] background', 'tags...",10781.66048,1.335204e+05,0.143574,0.323293,0.165663,0.100402,...,996.0,0.000000,1.0,epi_only,0.127576,0.026278,4.401777e+06,75.0,23.0,1.557481e+07
250325_F1_C1,None,LEDFlashTriggerPiezoControl_250325_F1_C1_Table...,iav-Gal4_+;+;UAS-Kir2_1,"{'text': 'IAV Kir2.1 in [+] background', 'tags...",6372.63770,6.254988e+04,0.212963,0.118519,0.231481,0.053704,...,540.0,0.000000,1.0,epi_only,0.174573,0.194133,1.965641e+06,14.0,8.0,1.249335e+07
250423_F1_C1,None,LEDFlashTriggerPiezoControl_250423_F1_C1_Table...,+;iav-Gal4_UAS-Kir2_1,"{'text': 'IAV Kir2.1 in [+] background', 'tags...",2441.71894,1.255256e+04,0.216495,0.113402,0.221649,0.082474,...,194.0,1.000000,1.0,epi_only,0.136435,0.045187,1.205903e+06,10.0,4.0,1.154684e+07
250423_F2_C1,None,LEDFlashTriggerPiezoControl_250423_F2_C1_Table...,+;iav-Gal4_UAS-Kir2_1,"{'text': 'IAV Kir2.1 in [+] background', 'tags...",6640.11538,2.175553e+05,0.078370,0.501567,0.103448,0.122257,...,638.0,0.000000,1.0,epi_only,0.206810,0.087918,7.784995e+06,69.0,8.0,1.582882e+07
250506_F1_C1,"Day 250506, F1, C1: LEDFlashTriggerPiezoContro...",LEDFlashTriggerPiezoControl_250506_F1_C1_Table...,+;UAS-Kir21;TH-GAL4,"{'text': 'TH>Kir2.1', 'tags': ['DANs', 'PPL', ...",7089.22006,2.068596e+05,0.217586,0.366617,0.156483,0.073025,...,671.0,1.000000,1.0,epi_only,0.093903,0.046601,8.283371e+06,34.0,17.0,2.849984e+07
250507_F1_C1,None,LEDFlashTriggerPiezoControl_250507_F1_C1_Table...,+;TH-Gal4_UAS-Kir2_1,"{'text': 'TH>Kir2.1', 'tags': ['DANs', 'PPL', ...",6671.31408,2.566297e+05,0.317597,0.412017,0.128755,0.090129,...,699.0,0.000000,1.0,epi_only,0.166237,0.064003,1.162105e+07,63.0,24.0,1.640085e+07
250507_F2_C1,None,LEDFlashTriggerPiezoControl_250507_F2_C1_Table...,+;TH-Gal4_UAS-Kir2_1,"{'text': 'TH>Kir2.1', 'tags': ['DANs', 'PPL', ...",6427.27412,1.784113e+05,0.197826,0.219565,0.228261,0.093478,...,460.0,0.000000,1.0,epi_only,0.157866,0.109811,1.504538e+07,32.0,11.0,2.438439e+07
250509_F1_C1,None,LEDFlashTriggerPiezoControl_250509_F1_C1_Table...,+;TH-Gal4_UAS-Kir2_1,"{'text': 'TH>Kir2.1', 'tags': ['DANs', 'PPL', ...",7315.63446,7.051660e+04,0.075758,0.111111,0.366162,0.035354,...,396.0,0.000000,1.0,epi_only,0.032645,0.033480,4.174487e+06,9.0,2.0,3.743606e+07
250509_F2_C1,None,LEDFlashTriggerPiezoControl_250509_F2_C1_Table...,+;TH-Gal4_UAS-Kir2_1,"{'text': 'TH>Kir2.1', 'tags': ['DANs', 'PPL', ...",8984.00136,9.699907e+04,0.306652,0.306652,0.152198,0.080045,...,887.0,0.000000,1.0,epi_only,0.270263,0.051518,3.230636e+06,65.0,25.0,1.260382e+07
250514_F1_C1,None,LEDFlashTriggerPiezoControl_250514_F1_C1_Table...,+;UAS-Kir21;TH-GAL4,"{'text': 'TH>Kir2.1', 'tags': ['DANs', 'PPL', ...",7162.92532,5.004122e+04,0.390278,0.212500,0.169444,0.093056,...,720.0,0.000000,1.0,epi_only,0.052191,0.192504,2.763766e+06,63.0,22.0,1.418251e+07
250515_F1_C1,None,LEDFlashTriggerPiezoControl_250515_F1_C1_Table...,+;TH-Gal4_pJFRC7,"{'text': 'TH>GFP', 'tags': ['control'], 'autho...",8646.53894,5.669057e+05,0.196450,0.307692,0.165680,0.043787,...,845.0,0.000000,1.0,epi_only,0.079460,0.052389,1.959599e+07,38.0,18.0,1.536301e+07
251114_F1_C2,None,LEDFlashTriggerPiezoControl_251114_F1_C2_Table...,+;UAS-TeTx;58E02-GAL4,"{'text': '58E02>UAS-Tetx', 'tags': ['DANs', 'P...",7669.67308,3.876924e+05,0.089032,0.672258,0.000000,0.184516,...,775.0,1.000000,1.0,epi_only,0.117578,0.114727,1.202397e+07,91.0,11.0,1.968081e+07
251217_F2_C1,None,LEDFlashTriggerPiezoControl_251217_F2_C1_Table...,iav_UAS-TeTx,"{'text': 'IAV TeTx in [+] background', 'tags':...",5823.91622,8.040643e+05,0.011532,0.866557,0.000000,0.121911,...,607.0,1.000000,1.0,epi_only,0.068425,0.030010,2.801166e+07,23.0,1.0,1.012131e+07
260527_F1_C1,None,LEDFlashTriggerPiezoControl_260527_F1_C1_Table...,PPL1_Tetx,"{'text': 'MB504B>UAS-Tetx', 'tags': ['DANs', '...",8300.71860,2.743926e+05,0.423469,0.270408,0.000000,0.121173,...,784.0,1.000000,1.0,epi_only,0.040564,0.091484,1.185811e+07,54.0,27.0,3.276110e+07
260527_F4_C1,None,LEDFlashTriggerPiezoControl_260527_F4_C1_Table...,PPL1_Tetx,"{'text': 'MB504B>UAS-Tetx', 'tags': ['DANs', '...",6061.92568,1.126651e+05,0.119565,0.400362,0.000000,0.222826,...,552.0,1.000000,1.0,epi_only,0.079367,0.050864,5.413262e+06,56.0,8.0,2.802886e+07
260605_F1_C1,None,LEDFlashTriggerPiezoControl_260605_F1_C1_Table...,+;UAS-TeTx;58E02-Gl4,"{'text': '58E02>UAS-Tetx', 'tags': ['DANs', 'P...",10462.74576,4.164796e+05,0.307615,0.376754,0.000000,0.147295,...,998.0,1.000000,1.0,epi_only,0.131255,0.099297,1.819335e+07,82.0,42.0,3.117517e+07
260605_F2_C1,None,LEDFlashTriggerPiezoControl_260605_F2_C1_Table...,+;UAS-TeTx;58E02-Gl4,"{'text': '58E02>UAS-Tetx', 'tags': ['DANs', 'P...",7591.12886,1.347467e+06,0.166436,0.475728,0.000000,0.166436,...,721.0,1.000000,1.0,epi_only,0.064538,0.068711,2.490475e+07,72.0,17.0,2.691578e+07
260605_F3_C1,None,LEDFlashTriggerPiezoControl_260605_F3_C1_Table...,+;UAS-TeTx;58E02-Gl4,"{'text': '58E02>UAS-Tetx', 'tags': ['DANs', 'P...",9231.40962,3.195984e+05,0.165195,0.373266,0.000000,0.142497,...,793.0,1.000000,1.0,epi_only,0.107207,0.048931,1.298272e+07,60.0,17.0,1.359398e+07

# +;TH-Gal4>GFP

### 250515_F1_C1

In [18]:
id = '250515_F1_C1'

# Note, tried training the fly initially.

# T = Table(f'LEDFlashTriggerPiezoControl_{id}_Table.parquet')
# T.assign_column_value('filtercube_status','green',trial_min=1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# sinq.add_table(table=T)
# sinq.df
# T.extract_trial_properties()
# fig,ax = T.plot_outcomes(savefig=True,format='png')
# fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')

# T = sinq.restore_table(id)
# poor_tracking = T.df.loc[750:]
# poor_tracking.index
# T.exclude_list_of_trials(poor_tracking.index,'poor_tracking')
# T.extract_trial_properties()
# fig,ax = T.plot_outcomes(savefig=True,format='png')
# fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')

sinq.set_note(
    dayflycell = id,
    text= 'TH>GFP',
    tags=['control'],
)

# 58E02 Manipulations

## 58E02>UAS-TeTx - TeTx silencing

### 251114_F1_C2

In [16]:
id = '251114_F1_C2'

# sinq,T = run_compute(sinq,id)
# run_plots(T)

sinq.set_note(
    dayflycell = id,
    text= '58E02>UAS-Tetx',
    tags=['DANs','PAM'],
)

### 260605_F1_C1

In [ ]:
# Standard plotting
def run_plots(T):
    fig,ax = T.plot_outcomes(savefig=True,format='png')
    fig,ax,df = T.plot_probe_position_heatmap(cmin=-500,cmax=10,format='png')

    df_filters = {'all':None,
              'hi':{'pyasState':'hi'},
              'lo':{'pyasState':'lo'},}

    for filt_key in df_filters.keys():
        dff = df_filters[filt_key]
        fig,ax = T.plot_probe_distribution(binwidth=2,bin_min=-500,bin_max=10,
                                df_filter=dff,index=None,savefig=False,format='png',
                                export=True)

In [15]:
id = '260605_F1_C1'

# T = T = Table(f'LEDFlashTriggerPiezoControl_{id}_Table.parquet')
# T.assign_column_value('filtercube_status','blue',trial_min=1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# T.extract_trial_properties()
# run_plots(T)

# sinq.add_table(table=T)
# # sinq.df
sinq.set_note(
    dayflycell = id,
    text= '58E02>UAS-Tetx',
    tags=['DANs','PAM'],
)

In [14]:
id = '260605_F2_C1'

# T = T = Table(f'LEDFlashTriggerPiezoControl_{id}_Table.parquet')
# T.assign_column_value('filtercube_status','blue',trial_min=1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# T.extract_trial_properties()
# run_plots(T)

# sinq.add_table(table=T)
# # sinq.df
sinq.set_note(
    dayflycell = id,
    text= '58E02>UAS-Tetx',
    tags=['DANs','PAM'],
)

In [13]:
id = '260605_F3_C1'

# T = Table(f'LEDFlashTriggerPiezoControl_{id}_Table.parquet')
# T.assign_column_value('filtercube_status','blue',trial_min=1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# end_of_day_trials = T.df.loc[806:]
# T.exclude_list_of_trials(end_of_day_trials.index,'just not watching')
# T.exclude_trials()

# T.extract_trial_properties()
# run_plots(T)

# sinq.add_table(table=T)
# sinq.df

sinq.set_note(
    dayflycell = id,
    text= '58E02>UAS-Tetx',
    tags=['DANs','PAM'],
)

# PPL1 - MB504B (https://splitgal4.janelia.org/precomputed/MB%20Paper%202014.html)

In [11]:
id = '260527_F1_C1'

# T = T = Table(f'LEDFlashTriggerPiezoControl_{id}_Table.parquet')
# T.assign_column_value('filtercube_status','blue',trial_min=1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# T.extract_trial_properties()
# run_plots(T)

# sinq.add_table(table=T)
# sinq.df

sinq.set_note(
    dayflycell = id,
    text= 'MB504B>UAS-Tetx',
    tags=['DANs','PPL'],
)

In [ ]:
id = '260527_F2_C1'
# THis one is bad, don't include

# T = T = Table(f'LEDFlashTriggerPiezoControl_{id}_Table.parquet')
# T.assign_column_value('filtercube_status','blue',trial_min=1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)

# T.extract_trial_properties()

# run_plots(T)
# sinq.add_table(table=T)
# sinq.df

In [9]:
id = '260527_F4_C1'

# T = T = Table(f'LEDFlashTriggerPiezoControl_{id}_Table.parquet')
# T.assign_column_value('filtercube_status','blue',trial_min=1, write_to_hdf5=True)
# T.assign_column_value('fiberLED','epi_only',trial_min =1,write_to_hdf5=True)
# T.extract_trial_properties()

# end_of_day_trials = T.df.loc[711:]
# T.exclude_list_of_trials(end_of_day_trials.index,'just not watching')
# T.exclude_trials()


# run_plots(T)
# sinq.add_table(table=T)
# sinq.df

sinq.set_note(
    dayflycell = id,
    text= 'MB504B>UAS-Tetx',
    tags=['DANs','PPL'],
)